import type {FormatValidationCase} from './types.ts';
import '@mionjs/ts-go-run-types/formats';
import {createValidate, createGetValidationErrors, createMockType, type DataOnly} from '@mionjs/ts-go-run-types';
import * as RT from '@mionjs/ts-go-run-types/schema';
import type {FormatNumber, FormatInteger, FormatFloat, FormatInt8, FormatUInt8} from '@mionjs/ts-go-run-types/formats';

export const NUMBER_FORMAT = {
  number_max: {
    title: 'FormatNumber<{max: 100}> — inclusive upper bound',
    validate: () => createValidate<FormatNumber<{max: 100}>>(),
    validateDataOnly: () => createValidate<DataOnly<FormatNumber<{max: 100}>>>(),
    validateSchema: () => createValidate(RT.number({max: 100})),
    getValidationErrors: () => createGetValidationErrors<FormatNumber<{max: 100}>>(),
    getValidationErrorsDataOnly: () => createGetValidationErrors<DataOnly<FormatNumber<{max: 100}>>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.number({max: 100})),
    mockType: () => createMockType<FormatNumber<{max: 100}>>(),
    getSamples: () => ({valid: [100, 0, -50], invalid: [101, '5']}),
    expectedFormatErrors: () => [{name: 'numberFormat', val: 100, formatPathTail: 'max'}, null],
  },
  number_min: {
    title: 'FormatNumber<{min: 0}> — inclusive lower bound',
    validate: () => createValidate<FormatNumber<{min: 0}>>(),
    validateDataOnly: () => createValidate<DataOnly<FormatNumber<{min: 0}>>>(),
    validateSchema: () => createValidate(RT.number({min: 0})),
    getValidationErrors: () => createGetValidationErrors<FormatNumber<{min: 0}>>(),
    getValidationErrorsDataOnly: () => createGetValidationErrors<DataOnly<FormatNumber<{min: 0}>>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.number({min: 0})),
    mockType: () => createMockType<FormatNumber<{min: 0}>>(),
    getSamples: () => ({valid: [0, 1, 9999], invalid: [-1]}),
    expectedFormatErrors: () => [{name: 'numberFormat', val: 0, formatPathTail: 'min'}],
  },
  number_lt: {
    title: 'FormatNumber<{lt: 10}> — exclusive upper bound',
    validate: () => createValidate<FormatNumber<{lt: 10}>>(),
    validateDataOnly: () => createValidate<DataOnly<FormatNumber<{lt: 10}>>>(),
    validateSchema: () => createValidate(RT.number({lt: 10})),
    getValidationErrors: () => createGetValidationErrors<FormatNumber<{lt: 10}>>(),
    getValidationErrorsDataOnly: () => createGetValidationErrors<DataOnly<FormatNumber<{lt: 10}>>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.number({lt: 10})),
    mockType: () => createMockType<FormatNumber<{lt: 10}>>(),
    getSamples: () => ({valid: [9, 0, -100], invalid: [10, 11]}),
    expectedFormatErrors: () => [
      {name: 'numberFormat', val: 10, formatPathTail: 'lt'},
      {name: 'numberFormat', val: 10, formatPathTail: 'lt'},
    ],
  },
  number_gt: {
    title: 'FormatNumber<{gt: 0}> — exclusive lower bound',
    validate: () => createValidate<FormatNumber<{gt: 0}>>(),
    validateDataOnly: () => createValidate<DataOnly<FormatNumber<{gt: 0}>>>(),
    validateSchema: () => createValidate(RT.number({gt: 0})),
    getValidationErrors: () => createGetValidationErrors<FormatNumber<{gt: 0}>>(),
    getValidationErrorsDataOnly: () => createGetValidationErrors<DataOnly<FormatNumber<{gt: 0}>>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.number({gt: 0})),
    mockType: () => createMockType<FormatNumber<{gt: 0}>>(),
    getSamples: () => ({valid: [1, 100], invalid: [0, -1]}),
    expectedFormatErrors: () => [
      {name: 'numberFormat', val: 0, formatPathTail: 'gt'},
      {name: 'numberFormat', val: 0, formatPathTail: 'gt'},
    ],
  },
  number_integer: {
    title: 'FormatInteger — whole numbers only',
    validate: () => createValidate<FormatInteger>(),
    validateDataOnly: () => createValidate<DataOnly<FormatInteger>>(),
    validateSchema: () => createValidate(RT.integer()),
    getValidationErrors: () => createGetValidationErrors<FormatInteger>(),
    getValidationErrorsDataOnly: () => createGetValidationErrors<DataOnly<FormatInteger>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.integer()),
    mockType: () => createMockType<FormatInteger>(),
    getSamples: () => ({valid: [0, 1, -1, 42], invalid: [1.5, 3.14]}),
    expectedFormatErrors: () => [
      {name: 'numberFormat', val: true, formatPathTail: 'integer'},
      {name: 'numberFormat', val: true, formatPathTail: 'integer'},
    ],
  },
  number_float: {
    title: 'FormatFloat — non-integer only',
    validate: () => createValidate<FormatFloat>(),
    validateDataOnly: () => createValidate<DataOnly<FormatFloat>>(),
    validateSchema: () => createValidate(RT.float()),
    getValidationErrors: () => createGetValidationErrors<FormatFloat>(),
    getValidationErrorsDataOnly: () => createGetValidationErrors<DataOnly<FormatFloat>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.float()),
    mockType: () => createMockType<FormatFloat>(),
    getSamples: () => ({valid: [1.5, -0.5, 3.14], invalid: [1, 0, -2]}),
    expectedFormatErrors: () => [
      {name: 'numberFormat', val: true, formatPathTail: 'float'},
      {name: 'numberFormat', val: true, formatPathTail: 'float'},
      {name: 'numberFormat', val: true, formatPathTail: 'float'},
    ],
  },
  number_multipleOf: {
    title: 'FormatNumber<{multipleOf: 5}> — divisible by 5',
    validate: () => createValidate<FormatNumber<{multipleOf: 5}>>(),
    validateDataOnly: () => createValidate<DataOnly<FormatNumber<{multipleOf: 5}>>>(),
    validateSchema: () => createValidate(RT.number({multipleOf: 5})),
    getValidationErrors: () => createGetValidationErrors<FormatNumber<{multipleOf: 5}>>(),
    getValidationErrorsDataOnly: () => createGetValidationErrors<DataOnly<FormatNumber<{multipleOf: 5}>>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.number({multipleOf: 5})),
    mockType: () => createMockType<FormatNumber<{multipleOf: 5}>>(),
    getSamples: () => ({valid: [0, 5, 10, -15], invalid: [3, 7]}),
    expectedFormatErrors: () => [
      {name: 'numberFormat', val: 5, formatPathTail: 'multipleOf'},
      {name: 'numberFormat', val: 5, formatPathTail: 'multipleOf'},
    ],
  },
  number_combined: {
    title: 'FormatNumber<{min:0; max:100; integer:true; multipleOf:5}> — all constraints',
    validate: () => createValidate<FormatNumber<{min: 0; max: 100; integer: true; multipleOf: 5}>>(),
    validateDataOnly: () => createValidate<DataOnly<FormatNumber<{min: 0; max: 100; integer: true; multipleOf: 5}>>>(),
    validateSchema: () => createValidate(RT.number({min: 0, max: 100, integer: true, multipleOf: 5})),
    getValidationErrors: () => createGetValidationErrors<FormatNumber<{min: 0; max: 100; integer: true; multipleOf: 5}>>(),
    getValidationErrorsDataOnly: () =>
      createGetValidationErrors<DataOnly<FormatNumber<{min: 0; max: 100; integer: true; multipleOf: 5}>>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.number({min: 0, max: 100, integer: true, multipleOf: 5})),
    mockType: () => createMockType<FormatNumber<{min: 0; max: 100; integer: true; multipleOf: 5}>>(),
    getSamples: () => ({valid: [0, 5, 50, 100], invalid: [-5, 105, 7, 2.5]}),
    expectedFormatErrors: () => [
      {name: 'numberFormat', formatPathTail: 'min'},
      {name: 'numberFormat', formatPathTail: 'max'},
      {name: 'numberFormat', formatPathTail: 'multipleOf'},
      {name: 'numberFormat', formatPathTail: 'integer'},
    ],
  },
  number_int8: {
    title: 'FormatInt8 — signed 8-bit range',
    validate: () => createValidate<FormatInt8>(),
    validateDataOnly: () => createValidate<DataOnly<FormatInt8>>(),
    validateSchema: () => createValidate(RT.int8()),
    getValidationErrors: () => createGetValidationErrors<FormatInt8>(),
    getValidationErrorsDataOnly: () => createGetValidationErrors<DataOnly<FormatInt8>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.int8()),
    mockType: () => createMockType<FormatInt8>(),
    getSamples: () => ({valid: [-128, 0, 127], invalid: [128, -129, 1.5]}),
    expectedFormatErrors: () => [
      {name: 'numberFormat', val: 127, formatPathTail: 'max'},
      {name: 'numberFormat', val: -128, formatPathTail: 'min'},
      {name: 'numberFormat', val: true, formatPathTail: 'integer'},
    ],
  },
  number_uint8: {
    title: 'FormatUInt8 — unsigned 8-bit range',
    validate: () => createValidate<FormatUInt8>(),
    validateDataOnly: () => createValidate<DataOnly<FormatUInt8>>(),
    validateSchema: () => createValidate(RT.uint8()),
    getValidationErrors: () => createGetValidationErrors<FormatUInt8>(),
    getValidationErrorsDataOnly: () => createGetValidationErrors<DataOnly<FormatUInt8>>(),
    getValidationErrorsSchema: () => createGetValidationErrors(RT.uint8()),
    mockType: () => createMockType<FormatUInt8>(),
    getSamples: () => ({valid: [0, 128, 255], invalid: [256, -1]}),
    expectedFormatErrors: () => [
      {name: 'numberFormat', val: 255, formatPathTail: 'max'},
      {name: 'numberFormat', val: 0, formatPathTail: 'min'},
    ],
  },
} as const satisfies Record<string, FormatValidationCase>;
