package main

import (
	"fmt"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/mionkit/ts-runtypes/internal/cachegen/operations"
	"github.com/mionkit/ts-runtypes/internal/constants"
)

// repoRoot is the ts-go-runtypes module root (two dirs up from this file).
func repoRoot() string {
	_, thisFile, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", ".."))
}

// fnHashesOutputPath is the absolute path of the TS file we emit.
func fnHashesOutputPath() string {
	return filepath.Join(repoRoot(), "packages", "ts-runtypes", "src", "fnHashes.generated.ts")
}

// axisToken maps an operation Axis onto its TS discriminator string.
func axisToken(axis operations.Axis) string {
	switch axis {
	case operations.AxisValidateOptions:
		return "validateOptions"
	case operations.AxisJsonStrategy:
		return "jsonStrategy"
	default:
		return "none"
	}
}

// fnHashEntry is one operation's rendered TS entry: its axis, the optional
// default variant (JSON strategy families only), and every variant token → hash.
type fnHashEntry struct {
	fnKey          string
	axis           string
	defaultVariant string
	variants       map[string]string
}

// validateSubsets returns the power set of ValidateOptions NAMES — every subset
// an it/te call site can request. Mirrors operations.validateOptionSubsets (kept
// local so the generator doesn't need an exported view of that internal helper).
func validateSubsets() [][]string {
	names := make([]string, 0, len(constants.ValidateOptions))
	for _, opt := range constants.ValidateOptions {
		names = append(names, opt.Name)
	}
	subsets := make([][]string, 0, 1<<len(names))
	for mask := 0; mask < (1 << len(names)); mask++ {
		var subset []string
		for i, name := range names {
			if mask&(1<<i) != 0 {
				subset = append(subset, name)
			}
		}
		subsets = append(subsets, subset)
	}
	return subsets
}

// collectEntries walks the operation registry and computes every (fnKey, variant
// token) → fnHash the runtime getFnHash resolver can be asked for. Skips any
// operation with no FnKey (none exist today, but the guard keeps the table keyed
// by the marker token the resolver receives).
func collectEntries() []fnHashEntry {
	entries := make([]fnHashEntry, 0, len(operations.All()))
	for _, op := range operations.All() {
		if op.FnKey == "" {
			continue
		}
		entry := fnHashEntry{fnKey: op.FnKey, axis: axisToken(op.Axis), variants: map[string]string{}}
		switch op.Axis {
		case operations.AxisValidateOptions:
			for _, subset := range validateSubsets() {
				token := constants.ValidateVariantSuffix(subset)
				entry.variants[token] = operations.FnHashFor(op, subset, "")
			}
		case operations.AxisJsonStrategy:
			entry.defaultVariant = op.DefaultStrategy
			for _, strategy := range op.Strategies {
				entry.variants[strategy] = operations.FnHashFor(op, nil, strategy)
			}
		default:
			entry.variants[""] = operations.FnHashFor(op, nil, "")
		}
		entries = append(entries, entry)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].fnKey < entries[j].fnKey })
	return entries
}

// tsKey renders an object key, quoting it when it isn't a bare JS identifier
// (the empty-string variant token and any future non-identifier token).
func tsKey(key string) string {
	if key != "" && isIdent(key) {
		return key
	}
	return fmt.Sprintf("%q", key)
}

func isIdent(s string) bool {
	for i, char := range s {
		isLetter := char == '_' || (char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z')
		isDigit := char >= '0' && char <= '9'
		if i == 0 && !isLetter {
			return false
		}
		if !isLetter && !isDigit {
			return false
		}
	}
	return len(s) > 0
}

// renderVariants renders a `{token: 'hash', …}` object with tokens sorted for
// deterministic output.
func renderVariants(variants map[string]string) string {
	tokens := make([]string, 0, len(variants))
	for token := range variants {
		tokens = append(tokens, token)
	}
	sort.Strings(tokens)
	parts := make([]string, 0, len(tokens))
	for _, token := range tokens {
		parts = append(parts, fmt.Sprintf("%s: %q", tsKey(token), variants[token]))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

// Generate returns the full TS module body mirroring the operation registry's
// version-independent fnHashes. Deterministic: same registry → same bytes, so
// the committed file and gen_test.go stay in lockstep.
func Generate() string {
	out := &strings.Builder{}
	out.WriteString("// Code generated by cmd/gen-fn-hashes. DO NOT EDIT.\n")
	out.WriteString("// Source: internal/cachegen/operations (the registry + fnhash.go salt).\n")
	out.WriteString("// Regenerate via `pnpm run gen:fn-hashes` after changing an operation, a\n")
	out.WriteString("// validate option, a JSON strategy, or the fnHash salt.\n")
	out.WriteString("//\n")
	out.WriteString("// Every fnHash here is VERSION-INDEPENDENT (operations.fnHashSalt no longer\n")
	out.WriteString("// folds constants.Version), so the same table ships for every ts-runtypes\n")
	out.WriteString("// release: a consumer resolves `fnKey (+ options) → fnHash` once and never\n")
	out.WriteString("// re-pins on a version bump. The runtime cache key is `<fnHash>_<typeId>`;\n")
	out.WriteString("// its typeId half (injected by the plugin) still carries the version.\n")
	out.WriteString("\n")

	out.WriteString("export type FnHashAxis = 'none' | 'validateOptions' | 'jsonStrategy';\n")
	out.WriteString("\n")
	out.WriteString("export interface FnHashEntry {\n")
	out.WriteString("  readonly axis: FnHashAxis;\n")
	out.WriteString("  /** jsonStrategy only: the strategy token applied when options omit `strategy`. */\n")
	out.WriteString("  readonly defaultVariant?: string;\n")
	out.WriteString("  /** Variant token → fnHash. Token is '' for option-less families, the validate\n")
	out.WriteString("   *  variant suffix ('', 'NL', 'NA', 'NLA'), or the JSON strategy name. */\n")
	out.WriteString("  readonly variants: Readonly<Record<string, string>>;\n")
	out.WriteString("}\n")
	out.WriteString("\n")

	out.WriteString("export const FN_HASHES = {\n")
	for _, entry := range collectEntries() {
		fields := []string{fmt.Sprintf("axis: %q", entry.axis)}
		if entry.defaultVariant != "" {
			fields = append(fields, fmt.Sprintf("defaultVariant: %q", entry.defaultVariant))
		}
		fields = append(fields, "variants: "+renderVariants(entry.variants))
		out.WriteString(fmt.Sprintf("  %s: {%s},\n", tsKey(entry.fnKey), strings.Join(fields, ", ")))
	}
	out.WriteString("} as const satisfies Record<string, FnHashEntry>;\n")
	out.WriteString("\n")

	out.WriteString("/** ValidateOptions name → single-letter token, in Go declaration order\n")
	out.WriteString(" *  (constants.ValidateOptions). The validate variant suffix is 'N' followed by\n")
	out.WriteString(" *  the letters of the present options concatenated in THIS order. */\n")
	out.WriteString("export const VALIDATE_OPTION_LETTERS = [\n")
	for _, opt := range constants.ValidateOptions {
		out.WriteString(fmt.Sprintf("  [%q, %q],\n", opt.Name, opt.Letter))
	}
	out.WriteString("] as const satisfies ReadonlyArray<readonly [string, string]>;\n")

	return out.String()
}
