// gen-ts-constants regenerates the TS mirror of internal/constants/constants.go.
//
// internal/constants/constants.go is the single source of truth for values
// shared across the Go and JS halves of this repo (cache module settings,
// reserved identifiers, …). This program imports that package and writes a
// TS module mirroring its values, so the JS workspace never duplicates the
// constants by hand.
//
// Output:
//
//   - packages/vite-plugin-runtypes/src/runtypes-constants.generated.ts
//     The registry consumed by the Vite plugin (cache modules, reflection
//     sub kinds, non-serializable globals).
//
// Run via the pnpm script:
//
//	pnpm run gen:ts-constants
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/mionkit/ts-run-types/internal/constants"
	"github.com/mionkit/ts-run-types/internal/protocol"
)

const vitePluginConstantsPath = "packages/vite-plugin-runtypes/src/runtypes-constants.generated.ts"

func main() {
	if err := writeFile(vitePluginConstantsPath, buildVitePluginConstants()); err != nil {
		fmt.Fprintln(os.Stderr, "gen-ts-constants:", err)
		os.Exit(1)
	}
}

// writeFile writes content to path, creating or overwriting.
func writeFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

// buildVitePluginConstants returns the full TS module body the Vite plugin
// consumes — cache modules, reflection sub kinds, and the non-serializable
// globals list.
func buildVitePluginConstants() string {
	out := &strings.Builder{}
	out.WriteString("// Code generated by cmd/gen-ts-constants. DO NOT EDIT.\n")
	out.WriteString("// Source: internal/constants/constants.go.\n")
	out.WriteString("// Regenerate via `pnpm run gen:ts-constants` after changing the Go source.\n")
	out.WriteString("\n")

	out.WriteString("export interface CacheModuleSettings {\n")
	out.WriteString("  readonly name: string;\n")
	out.WriteString("  readonly varPrefix: string;\n")
	out.WriteString("  readonly tag: string;\n")
	out.WriteString("}\n")
	out.WriteString("\n")

	keys := make([]string, 0, len(constants.CacheModules))
	for key := range constants.CacheModules {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	out.WriteString("export const CACHE_MODULES = {\n")
	for _, key := range keys {
		setting := constants.CacheModules[key]
		out.WriteString(fmt.Sprintf("  %s: {name: %q, varPrefix: %q, tag: %q},\n", tsKey(key), setting.Name, setting.VarPrefix, setting.Tag))
	}
	out.WriteString("} as const satisfies Record<string, CacheModuleSettings>;\n")
	out.WriteString("\n")

	// Convenience exports per module — `RUNTYPES_VAR_PREFIX` etc. — so
	// callers don't have to dereference CACHE_MODULES at every use site.
	for _, key := range keys {
		setting := constants.CacheModules[key]
		upper := strings.ToUpper(key)
		out.WriteString(fmt.Sprintf("export const %s_VAR_PREFIX = %q;\n", upper, setting.VarPrefix))
		out.WriteString(fmt.Sprintf("export const %s_MODULE_NAME = %q;\n", upper, setting.Name))
		out.WriteString(fmt.Sprintf("export const %s_TAG = %q;\n", upper, setting.Tag))
	}

	out.WriteString("\n")
	writeEntryModuleConstants(out)
	out.WriteString("\n")
	writeReflectionSubKind(out)
	out.WriteString("\n")
	writeNonSerializableGlobals(out)

	return out.String()
}

// writeEntryModuleConstants emits the per-entry virtual-module settings the
// plugin's resolveId/load hooks and the rewrite's import injection consume.
func writeEntryModuleConstants(out *strings.Builder) {
	out.WriteString("// Per-entry virtual-module settings — see internal/compiled/entrymod.\n")
	fmt.Fprintf(out, "export const VIRTUAL_MODULE_PREFIX = %q;\n", constants.VirtualModulePrefix)
	fmt.Fprintf(out, "export const ENTRY_MODULE_SUFFIX = %q;\n", constants.EntryModuleSuffix)
	fmt.Fprintf(out, "export const ENTRY_BINDING_PREFIX = %q;\n", constants.EntryBindingPrefix)
	fmt.Fprintf(out, "export const PURE_FN_MODULE_DIR = %q;\n", constants.PureFnModuleDir)
	fmt.Fprintf(out, "export const RUNTYPES_BUNDLE_BASENAME = %q;\n", constants.RunTypesBundleBasename)
	fmt.Fprintf(out, "export const FNS_BUNDLE_DIR = %q;\n", constants.FnsBundleDir)
	out.WriteString("// Module-mode values for the --module-mode flag / plugin moduleMode option.\n")
	fmt.Fprintf(out, "export const MODULE_MODE_DEFAULT = %q;\n", constants.ModuleModeDefault)
	fmt.Fprintf(out, "export const MODULE_MODE_ALL_SINGLE = %q;\n", constants.ModuleModeAllSingle)
	fmt.Fprintf(out, "export const MODULE_MODE_ALL_MODULES = %q;\n", constants.ModuleModeAllModules)
	out.WriteString("export type ModuleMode = typeof MODULE_MODE_DEFAULT | typeof MODULE_MODE_ALL_SINGLE | typeof MODULE_MODE_ALL_MODULES;\n")
}

// writeReflectionSubKind emits a TS `as const` map mirroring
// internal/protocol/subkind.go's ReflectionSubKind enum. The numeric
// values must match mion's own ReflectionSubKind exactly so structural
// ids agree byte-for-byte across the Go and TS halves.
func writeReflectionSubKind(out *strings.Builder) {
	entries := []struct {
		name  string
		value protocol.ReflectionSubKind
	}{
		{"mapKey", protocol.SubKindMapKey},
		{"mapValue", protocol.SubKindMapValue},
		{"setItem", protocol.SubKindSetItem},
		{"date", protocol.SubKindDate},
		{"map", protocol.SubKindMap},
		{"set", protocol.SubKindSet},
		{"nonSerializable", protocol.SubKindNonSerializable},
	}
	out.WriteString("export const REFLECTION_SUB_KIND = {\n")
	for _, entry := range entries {
		out.WriteString(fmt.Sprintf("  %s: %d,\n", entry.name, entry.value))
	}
	out.WriteString("} as const;\n")
	out.WriteString("export type ReflectionSubKind = (typeof REFLECTION_SUB_KIND)[keyof typeof REFLECTION_SUB_KIND];\n")
}

// writeNonSerializableGlobals emits the symbol-name list used by both
// halves to detect non-serialisable native types. Mirrors mion's
// `nonSerializableGlobals` in `packages/run-types/src/constants.ts`.
func writeNonSerializableGlobals(out *strings.Builder) {
	out.WriteString("export const NON_SERIALIZABLE_GLOBALS = [\n")
	for _, name := range protocol.NonSerializableGlobals {
		out.WriteString(fmt.Sprintf("  %q,\n", name))
	}
	out.WriteString("] as const;\n")
}

// tsKey wraps a key in quotes if it isn't a bare JS identifier. Keeps the
// generated object literal small for the common alphanumeric case.
func tsKey(key string) string {
	if isIdent(key) {
		return key
	}
	return fmt.Sprintf("%q", key)
}

func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, char := range s {
		isLetter := char == '_' || (char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z')
		isDigit := char >= '0' && char <= '9'
		if i == 0 && !isLetter {
			return false
		}
		if !isLetter && !isDigit {
			return false
		}
	}
	return true
}
