// gen-ts-constants regenerates the TS mirror of internal/constants/constants.go.
//
// internal/constants/constants.go is the single source of truth for values
// shared across the Go and JS halves of this repo (cache module settings,
// reserved identifiers, …). This program imports that package and prints
// a TS module mirroring its values, so the JS workspace never duplicates
// the constants by hand.
//
// Run:
//
//	go run ./cmd/gen-ts-constants > packages/vite-plugin-runtypes/src/runtypes-constants.generated.ts
//
// Or via the pnpm script:
//
//	pnpm run gen:ts-constants
package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mionkit/ts-run-types/internal/constants"
)

func main() {
	out := &strings.Builder{}
	out.WriteString("// Code generated by cmd/gen-ts-constants. DO NOT EDIT.\n")
	out.WriteString("// Source: internal/constants/constants.go.\n")
	out.WriteString("// Regenerate via `pnpm run gen:ts-constants` after changing the Go source.\n")
	out.WriteString("\n")

	out.WriteString("export interface CacheModuleSettings {\n")
	out.WriteString("  readonly name: string;\n")
	out.WriteString("  readonly varPrefix: string;\n")
	out.WriteString("}\n")
	out.WriteString("\n")

	keys := make([]string, 0, len(constants.CacheModules))
	for key := range constants.CacheModules {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	out.WriteString("export const CACHE_MODULES = {\n")
	for _, key := range keys {
		setting := constants.CacheModules[key]
		out.WriteString(fmt.Sprintf("  %s: {name: %q, varPrefix: %q},\n", tsKey(key), setting.Name, setting.VarPrefix))
	}
	out.WriteString("} as const satisfies Record<string, CacheModuleSettings>;\n")
	out.WriteString("\n")

	// Convenience exports per module — `RUNTYPES_VAR_PREFIX` etc. — so
	// callers don't have to dereference CACHE_MODULES at every use site.
	for _, key := range keys {
		setting := constants.CacheModules[key]
		upper := strings.ToUpper(key)
		out.WriteString(fmt.Sprintf("export const %s_VAR_PREFIX = %q;\n", upper, setting.VarPrefix))
		out.WriteString(fmt.Sprintf("export const %s_MODULE_NAME = %q;\n", upper, setting.Name))
	}

	fmt.Print(out.String())
}

// tsKey wraps a key in quotes if it isn't a bare JS identifier. Keeps the
// generated object literal small for the common alphanumeric case.
func tsKey(key string) string {
	if isIdent(key) {
		return key
	}
	return fmt.Sprintf("%q", key)
}

func isIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, char := range s {
		isLetter := char == '_' || (char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z')
		isDigit := char >= '0' && char <= '9'
		if i == 0 && !isLetter {
			return false
		}
		if !isLetter && !isDigit {
			return false
		}
	}
	return true
}

