import * as TF from 'ts-runtypes/formats';
import type {SerializationCase} from './types.ts';
import 'ts-runtypes/formats';
import {createBinaryDecoder, createBinaryEncoder, createJsonDecoder, createJsonEncoder} from 'ts-runtypes';

export const NUMBER_FORMAT = {
  number_int8: {
    title: 'Int8',
    description:
      'JSON + binary (de)serialization of TF.Int8 (number branded {integer:true; min:-128; max:127}); the [-128,127] bounds select a 1-byte signed binary encoding while JSON writes the plain number, packing every value into 1 byte.',
    serializeNotes:
      'Format-aware binary width: the int8 bounds pin every value to a single byte (getBinaryByteSizes [1,1,1]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<TF.Int8>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<TF.Int8>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<TF.Int8>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<TF.Int8>(),
    preserveDecoder: () => createJsonDecoder<TF.Int8>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<TF.Int8>(),
    binaryDecoder: () => createBinaryDecoder<TF.Int8>(),
    schemaEncoder: () => createJsonEncoder(TF.int8()),
    schemaDecoder: () => createJsonDecoder(TF.int8()),
    schemaBinaryEncoder: () => createBinaryEncoder(TF.int8()),
    schemaBinaryDecoder: () => createBinaryDecoder(TF.int8()),
    getTestData: () => ({values: [-128, 0, 127]}),
    getBinaryByteSizes: () => [1, 1, 1],
  },
  number_int16: {
    title: 'Int16',
    description:
      'JSON + binary (de)serialization of TF.Int16 (number branded {integer:true; min:-32768; max:32767}); the [-32768,32767] bounds select a 2-byte signed binary encoding while JSON writes the plain number, packing every value into 2 bytes.',
    serializeNotes:
      'Format-aware binary width: the int16 bounds fix each value at 2 bytes (getBinaryByteSizes [2,2,2]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<TF.Int16>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<TF.Int16>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<TF.Int16>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<TF.Int16>(),
    preserveDecoder: () => createJsonDecoder<TF.Int16>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<TF.Int16>(),
    binaryDecoder: () => createBinaryDecoder<TF.Int16>(),
    schemaEncoder: () => createJsonEncoder(TF.int16()),
    schemaDecoder: () => createJsonDecoder(TF.int16()),
    schemaBinaryEncoder: () => createBinaryEncoder(TF.int16()),
    schemaBinaryDecoder: () => createBinaryDecoder(TF.int16()),
    getTestData: () => ({values: [-32768, 0, 32767]}),
    getBinaryByteSizes: () => [2, 2, 2],
  },
  number_int32: {
    title: 'Int32',
    description:
      'JSON + binary (de)serialization of TF.Int32 (number branded {integer:true; min:-2147483648; max:2147483647}); the 32-bit bounds select a 4-byte signed binary encoding while JSON writes the plain number, packing every value into 4 bytes.',
    serializeNotes:
      'Format-aware binary width: the int32 bounds fix each value at 4 bytes (getBinaryByteSizes [4,4,4]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<TF.Int32>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<TF.Int32>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<TF.Int32>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<TF.Int32>(),
    preserveDecoder: () => createJsonDecoder<TF.Int32>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<TF.Int32>(),
    binaryDecoder: () => createBinaryDecoder<TF.Int32>(),
    schemaEncoder: () => createJsonEncoder(TF.int32()),
    schemaDecoder: () => createJsonDecoder(TF.int32()),
    schemaBinaryEncoder: () => createBinaryEncoder(TF.int32()),
    schemaBinaryDecoder: () => createBinaryDecoder(TF.int32()),
    getTestData: () => ({values: [-2147483648, 0, 2147483647]}),
    getBinaryByteSizes: () => [4, 4, 4],
  },
  number_uint8: {
    title: 'UInt8',
    description:
      'JSON + binary (de)serialization of TF.UInt8 (number branded {integer:true; min:0; max:255}); the [0,255] bounds select a 1-byte unsigned binary encoding while JSON writes the plain number, packing every value into 1 byte.',
    serializeNotes:
      'Format-aware binary width: the unsigned 8-bit bounds fix each value at 1 byte (getBinaryByteSizes [1,1,1]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<TF.UInt8>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<TF.UInt8>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<TF.UInt8>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<TF.UInt8>(),
    preserveDecoder: () => createJsonDecoder<TF.UInt8>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<TF.UInt8>(),
    binaryDecoder: () => createBinaryDecoder<TF.UInt8>(),
    schemaEncoder: () => createJsonEncoder(TF.uint8()),
    schemaDecoder: () => createJsonDecoder(TF.uint8()),
    schemaBinaryEncoder: () => createBinaryEncoder(TF.uint8()),
    schemaBinaryDecoder: () => createBinaryDecoder(TF.uint8()),
    getTestData: () => ({values: [0, 128, 255]}),
    getBinaryByteSizes: () => [1, 1, 1],
  },
  number_uint16: {
    title: 'UInt16',
    description:
      'JSON + binary (de)serialization of TF.UInt16 (number branded {integer:true; min:0; max:65535}); the [0,65535] bounds select a 2-byte unsigned binary encoding while JSON writes the plain number, packing every value into 2 bytes.',
    serializeNotes:
      'Format-aware binary width: the unsigned 16-bit bounds fix each value at 2 bytes (getBinaryByteSizes [2,2,2]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<TF.UInt16>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<TF.UInt16>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<TF.UInt16>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<TF.UInt16>(),
    preserveDecoder: () => createJsonDecoder<TF.UInt16>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<TF.UInt16>(),
    binaryDecoder: () => createBinaryDecoder<TF.UInt16>(),
    schemaEncoder: () => createJsonEncoder(TF.uint16()),
    schemaDecoder: () => createJsonDecoder(TF.uint16()),
    schemaBinaryEncoder: () => createBinaryEncoder(TF.uint16()),
    schemaBinaryDecoder: () => createBinaryDecoder(TF.uint16()),
    getTestData: () => ({values: [0, 32768, 65535]}),
    getBinaryByteSizes: () => [2, 2, 2],
  },
  number_uint32: {
    title: 'UInt32',
    description:
      'JSON + binary (de)serialization of TF.UInt32 (number branded {integer:true; min:0; max:4294967295}); the 32-bit unsigned bounds select a 4-byte binary encoding while JSON writes the plain number, packing every value into 4 bytes.',
    serializeNotes:
      'Format-aware binary width: the unsigned 32-bit bounds fix each value at 4 bytes (getBinaryByteSizes [4,4,4]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<TF.UInt32>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<TF.UInt32>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<TF.UInt32>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<TF.UInt32>(),
    preserveDecoder: () => createJsonDecoder<TF.UInt32>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<TF.UInt32>(),
    binaryDecoder: () => createBinaryDecoder<TF.UInt32>(),
    schemaEncoder: () => createJsonEncoder(TF.uint32()),
    schemaDecoder: () => createJsonDecoder(TF.uint32()),
    schemaBinaryEncoder: () => createBinaryEncoder(TF.uint32()),
    schemaBinaryDecoder: () => createBinaryDecoder(TF.uint32()),
    getTestData: () => ({values: [0, 2147483648, 4294967295]}),
    getBinaryByteSizes: () => [4, 4, 4],
  },
  number_integer_8bytes: {
    title: 'Integer',
    description:
      'JSON + binary (de)serialization of TF.Integer (number branded {integer:true}, no min/max); with no bounds to narrow the width, this unbounded integer falls back to a full float64 (8 bytes) in binary and JSON writes the plain number, with samples including MAX_SAFE_INTEGER / MIN_SAFE_INTEGER.',
    serializeNotes:
      'No bounds → no width optimization: binary uses float64 8 bytes regardless of value (getBinaryByteSizes [8,8,8]); safe-integer extremes still round-trip losslessly in both JSON and binary.',
    mutateEncoder: () => createJsonEncoder<TF.Integer>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<TF.Integer>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<TF.Integer>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<TF.Integer>(),
    preserveDecoder: () => createJsonDecoder<TF.Integer>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<TF.Integer>(),
    binaryDecoder: () => createBinaryDecoder<TF.Integer>(),
    schemaEncoder: () => createJsonEncoder(TF.integer()),
    schemaDecoder: () => createJsonDecoder(TF.integer()),
    schemaBinaryEncoder: () => createBinaryEncoder(TF.integer()),
    schemaBinaryDecoder: () => createBinaryDecoder(TF.integer()),
    getTestData: () => ({values: [10, Number.MAX_SAFE_INTEGER, Number.MIN_SAFE_INTEGER]}),
    getBinaryByteSizes: () => [8, 8, 8],
  },
  number_float_8bytes: {
    title: 'Float',
    description:
      'JSON + binary (de)serialization of TF.Float (number branded {float:true}); floats encode as a full float64 (8 bytes) in binary and as the plain number in JSON, with samples including a negative and an exponent literal (1.23e10).',
    serializeNotes:
      'Float values always take 8 bytes in binary (getBinaryByteSizes [8,8,8]) — no integer-width narrowing applies; both formats round-trip losslessly.',
    mutateEncoder: () => createJsonEncoder<TF.Float>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<TF.Float>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<TF.Float>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<TF.Float>(),
    preserveDecoder: () => createJsonDecoder<TF.Float>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<TF.Float>(),
    binaryDecoder: () => createBinaryDecoder<TF.Float>(),
    schemaEncoder: () => createJsonEncoder(TF.float()),
    schemaDecoder: () => createJsonDecoder(TF.float()),
    schemaBinaryEncoder: () => createBinaryEncoder(TF.float()),
    schemaBinaryDecoder: () => createBinaryDecoder(TF.float()),
    getTestData: () => ({values: [10.5, -3.14, 1.23e10]}),
    getBinaryByteSizes: () => [8, 8, 8],
  },
  number_ranged: {
    title: 'Ranged Integer',
    description:
      'JSON + binary (de)serialization of an ad-hoc ranged TF.Number {min:0; max:1000; integer:true} (not one of the named int aliases); binary picks the narrowest unsigned width that fits [0,1000] — uint16 (2 bytes) — while JSON writes the plain number.',
    serializeNotes:
      'Format-aware binary width is derived from arbitrary bounds, not just the named int formats: [0,1000] integer fits uint16, so each value packs into 2 bytes (getBinaryByteSizes [2,2,2]).',
    mutateEncoder: () => createJsonEncoder<TF.Number<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<TF.Number<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<TF.Number<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<TF.Number<{min: 0; max: 1000; integer: true}>>(),
    preserveDecoder: () => createJsonDecoder<TF.Number<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<TF.Number<{min: 0; max: 1000; integer: true}>>(),
    binaryDecoder: () => createBinaryDecoder<TF.Number<{min: 0; max: 1000; integer: true}>>(),
    schemaEncoder: () => createJsonEncoder(TF.number({min: 0, max: 1000, integer: true})),
    schemaDecoder: () => createJsonDecoder(TF.number({min: 0, max: 1000, integer: true})),
    schemaBinaryEncoder: () => createBinaryEncoder(TF.number({min: 0, max: 1000, integer: true})),
    schemaBinaryDecoder: () => createBinaryDecoder(TF.number({min: 0, max: 1000, integer: true})),
    getTestData: () => ({values: [0, 500, 1000]}),
    getBinaryByteSizes: () => [2, 2, 2],
  },
} as const satisfies Record<string, SerializationCase>;
