import {createBinaryDecoder, createBinaryEncoder, createJsonDecoder, createJsonEncoder} from '@mionjs/ts-go-run-types';
import type {SerializationCase} from './types.ts';

export const OTHERS = {
  promise_jsonStringify_error: {
    title: 'Promise top-level throws',
    unsafeEncoder: () => createJsonEncoder<Promise<string>>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<Promise<string>>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<Promise<string>>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<Promise<string>>(),
    safeDirectEncoder: () => createJsonEncoder<Promise<string>>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<Promise<string>>(),
    unsafeDecoder: () => createJsonDecoder<Promise<string>>(undefined, {strategy: 'mutate', stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<Promise<string>>(),
    binaryDecoder: () => createBinaryDecoder<Promise<string>>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
  non_serializable: {
    title: 'non-serializable type throws (Int8Array)',
    unsafeEncoder: () => createJsonEncoder<Int8Array>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<Int8Array>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<Int8Array>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<Int8Array>(),
    safeDirectEncoder: () => createJsonEncoder<Int8Array>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<Int8Array>(),
    unsafeDecoder: () => createJsonDecoder<Int8Array>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<Int8Array>(),
    binaryDecoder: () => createBinaryDecoder<Int8Array>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
  non_serializable_interface: {
    title: 'non-serializable inside interface throws',
    unsafeEncoder: () => createJsonEncoder<{a: Int8Array}>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<{a: Int8Array}>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<{a: Int8Array}>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<{a: Int8Array}>(),
    safeDirectEncoder: () => createJsonEncoder<{a: Int8Array}>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<{a: Int8Array}>(),
    unsafeDecoder: () => createJsonDecoder<{a: Int8Array}>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<{a: Int8Array}>(),
    binaryDecoder: () => createBinaryDecoder<{a: Int8Array}>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
  non_serializable_array: {
    title: 'non-serializable inside array throws',
    unsafeEncoder: () => createJsonEncoder<Int8Array[]>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<Int8Array[]>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<Int8Array[]>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<Int8Array[]>(),
    safeDirectEncoder: () => createJsonEncoder<Int8Array[]>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<Int8Array[]>(),
    unsafeDecoder: () => createJsonDecoder<Int8Array[]>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<Int8Array[]>(),
    binaryDecoder: () => createBinaryDecoder<Int8Array[]>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
  non_serializable_tuple: {
    title: 'non-serializable inside tuple throws',
    unsafeEncoder: () => createJsonEncoder<[Int8Array]>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<[Int8Array]>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<[Int8Array]>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<[Int8Array]>(),
    safeDirectEncoder: () => createJsonEncoder<[Int8Array]>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<[Int8Array]>(),
    unsafeDecoder: () => createJsonDecoder<[Int8Array]>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<[Int8Array]>(),
    binaryDecoder: () => createBinaryDecoder<[Int8Array]>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
} as const satisfies Record<string, SerializationCase>;
