import {createBinaryDecoder, createBinaryEncoder, createJsonDecoder, createJsonEncoder} from '@mionjs/ts-go-run-types';
import type {SerializationCase} from './types.ts';

export const OTHERS = {
  promise_jsonStringify_error: {
    title: 'Promise top-level throws',
    mutateEncoder: () => createJsonEncoder<Promise<string>>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<Promise<string>>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<Promise<string>>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<Promise<string>>(),
    directEncoder: () => createJsonEncoder<Promise<string>>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<Promise<string>>(),
    preserveDecoder: () => createJsonDecoder<Promise<string>>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<Promise<string>>(),
    binaryDecoder: () => createBinaryDecoder<Promise<string>>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
  non_serializable: {
    title: 'non-serializable type throws (Int8Array)',
    mutateEncoder: () => createJsonEncoder<Int8Array>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<Int8Array>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<Int8Array>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<Int8Array>(),
    directEncoder: () => createJsonEncoder<Int8Array>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<Int8Array>(),
    preserveDecoder: () => createJsonDecoder<Int8Array>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<Int8Array>(),
    binaryDecoder: () => createBinaryDecoder<Int8Array>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
  non_serializable_interface: {
    title: 'non-serializable inside interface throws',
    mutateEncoder: () => createJsonEncoder<{a: Int8Array}>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<{a: Int8Array}>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<{a: Int8Array}>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<{a: Int8Array}>(),
    directEncoder: () => createJsonEncoder<{a: Int8Array}>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<{a: Int8Array}>(),
    preserveDecoder: () => createJsonDecoder<{a: Int8Array}>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<{a: Int8Array}>(),
    binaryDecoder: () => createBinaryDecoder<{a: Int8Array}>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
  non_serializable_array: {
    title: 'non-serializable inside array throws',
    mutateEncoder: () => createJsonEncoder<Int8Array[]>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<Int8Array[]>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<Int8Array[]>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<Int8Array[]>(),
    directEncoder: () => createJsonEncoder<Int8Array[]>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<Int8Array[]>(),
    preserveDecoder: () => createJsonDecoder<Int8Array[]>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<Int8Array[]>(),
    binaryDecoder: () => createBinaryDecoder<Int8Array[]>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
  non_serializable_tuple: {
    title: 'non-serializable inside tuple throws',
    mutateEncoder: () => createJsonEncoder<[Int8Array]>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<[Int8Array]>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<[Int8Array]>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<[Int8Array]>(),
    directEncoder: () => createJsonEncoder<[Int8Array]>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<[Int8Array]>(),
    preserveDecoder: () => createJsonDecoder<[Int8Array]>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<[Int8Array]>(),
    binaryDecoder: () => createBinaryDecoder<[Int8Array]>(),
    factoryThrows: true,
    getTestData: () => ({values: []}),
  },
} as const satisfies Record<string, SerializationCase>;
