import type {SerializationCase} from './types.ts';
import * as RT from '@mionjs/ts-go-run-types/schema';
import '@mionjs/ts-go-run-types/formats';
import {createBinaryDecoder, createBinaryEncoder, createJsonDecoder, createJsonEncoder} from '@mionjs/ts-go-run-types';
import type {
  FormatNumber,
  FormatInteger,
  FormatFloat,
  FormatInt8,
  FormatInt16,
  FormatInt32,
  FormatUInt8,
  FormatUInt16,
  FormatUInt32,
} from '@mionjs/ts-go-run-types/formats';

export const NUMBER_FORMAT = {
  number_int8: {
    title: 'FormatInt8 — packs into 1 byte',
    description:
      'JSON + binary (de)serialization of FormatInt8 (number branded {integer:true; min:-128; max:127}); the [-128,127] bounds select a 1-byte signed binary encoding while JSON writes the plain number.',
    serializeNotes: 'Format-aware binary width: the int8 bounds pin every value to a single byte (getBinaryByteSizes [1,1,1]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<FormatInt8>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatInt8>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<FormatInt8>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatInt8>(),
    preserveDecoder: () => createJsonDecoder<FormatInt8>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatInt8>(),
    binaryDecoder: () => createBinaryDecoder<FormatInt8>(),
    schemaEncoder: () => createJsonEncoder(RT.int8()),
    schemaDecoder: () => createJsonDecoder(RT.int8()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.int8()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.int8()),
    getTestData: () => ({values: [-128, 0, 127]}),
    getBinaryByteSizes: () => [1, 1, 1],
  },
  number_int16: {
    title: 'FormatInt16 — packs into 2 bytes',
    description:
      'JSON + binary (de)serialization of FormatInt16 (number branded {integer:true; min:-32768; max:32767}); the [-32768,32767] bounds select a 2-byte signed binary encoding while JSON writes the plain number.',
    serializeNotes: 'Format-aware binary width: the int16 bounds fix each value at 2 bytes (getBinaryByteSizes [2,2,2]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<FormatInt16>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatInt16>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<FormatInt16>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatInt16>(),
    preserveDecoder: () => createJsonDecoder<FormatInt16>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatInt16>(),
    binaryDecoder: () => createBinaryDecoder<FormatInt16>(),
    schemaEncoder: () => createJsonEncoder(RT.int16()),
    schemaDecoder: () => createJsonDecoder(RT.int16()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.int16()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.int16()),
    getTestData: () => ({values: [-32768, 0, 32767]}),
    getBinaryByteSizes: () => [2, 2, 2],
  },
  number_int32: {
    title: 'FormatInt32 — packs into 4 bytes',
    description:
      'JSON + binary (de)serialization of FormatInt32 (number branded {integer:true; min:-2147483648; max:2147483647}); the 32-bit bounds select a 4-byte signed binary encoding while JSON writes the plain number.',
    serializeNotes: 'Format-aware binary width: the int32 bounds fix each value at 4 bytes (getBinaryByteSizes [4,4,4]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<FormatInt32>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatInt32>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<FormatInt32>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatInt32>(),
    preserveDecoder: () => createJsonDecoder<FormatInt32>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatInt32>(),
    binaryDecoder: () => createBinaryDecoder<FormatInt32>(),
    schemaEncoder: () => createJsonEncoder(RT.int32()),
    schemaDecoder: () => createJsonDecoder(RT.int32()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.int32()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.int32()),
    getTestData: () => ({values: [-2147483648, 0, 2147483647]}),
    getBinaryByteSizes: () => [4, 4, 4],
  },
  number_uint8: {
    title: 'FormatUInt8 — packs into 1 byte',
    description:
      'JSON + binary (de)serialization of FormatUInt8 (number branded {integer:true; min:0; max:255}); the [0,255] bounds select a 1-byte unsigned binary encoding while JSON writes the plain number.',
    serializeNotes: 'Format-aware binary width: the unsigned 8-bit bounds fix each value at 1 byte (getBinaryByteSizes [1,1,1]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<FormatUInt8>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatUInt8>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<FormatUInt8>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatUInt8>(),
    preserveDecoder: () => createJsonDecoder<FormatUInt8>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatUInt8>(),
    binaryDecoder: () => createBinaryDecoder<FormatUInt8>(),
    schemaEncoder: () => createJsonEncoder(RT.uint8()),
    schemaDecoder: () => createJsonDecoder(RT.uint8()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.uint8()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.uint8()),
    getTestData: () => ({values: [0, 128, 255]}),
    getBinaryByteSizes: () => [1, 1, 1],
  },
  number_uint16: {
    title: 'FormatUInt16 — packs into 2 bytes',
    description:
      'JSON + binary (de)serialization of FormatUInt16 (number branded {integer:true; min:0; max:65535}); the [0,65535] bounds select a 2-byte unsigned binary encoding while JSON writes the plain number.',
    serializeNotes: 'Format-aware binary width: the unsigned 16-bit bounds fix each value at 2 bytes (getBinaryByteSizes [2,2,2]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<FormatUInt16>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatUInt16>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<FormatUInt16>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatUInt16>(),
    preserveDecoder: () => createJsonDecoder<FormatUInt16>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatUInt16>(),
    binaryDecoder: () => createBinaryDecoder<FormatUInt16>(),
    schemaEncoder: () => createJsonEncoder(RT.uint16()),
    schemaDecoder: () => createJsonDecoder(RT.uint16()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.uint16()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.uint16()),
    getTestData: () => ({values: [0, 32768, 65535]}),
    getBinaryByteSizes: () => [2, 2, 2],
  },
  number_uint32: {
    title: 'FormatUInt32 — packs into 4 bytes',
    description:
      'JSON + binary (de)serialization of FormatUInt32 (number branded {integer:true; min:0; max:4294967295}); the 32-bit unsigned bounds select a 4-byte binary encoding while JSON writes the plain number.',
    serializeNotes: 'Format-aware binary width: the unsigned 32-bit bounds fix each value at 4 bytes (getBinaryByteSizes [4,4,4]); JSON is lossless plain-number text.',
    mutateEncoder: () => createJsonEncoder<FormatUInt32>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatUInt32>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<FormatUInt32>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatUInt32>(),
    preserveDecoder: () => createJsonDecoder<FormatUInt32>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatUInt32>(),
    binaryDecoder: () => createBinaryDecoder<FormatUInt32>(),
    schemaEncoder: () => createJsonEncoder(RT.uint32()),
    schemaDecoder: () => createJsonDecoder(RT.uint32()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.uint32()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.uint32()),
    getTestData: () => ({values: [0, 2147483648, 4294967295]}),
    getBinaryByteSizes: () => [4, 4, 4],
  },
  number_integer_8bytes: {
    title: 'FormatInteger — unbounded integer falls back to float64 (8 bytes)',
    description:
      'JSON + binary (de)serialization of FormatInteger (number branded {integer:true}, no min/max); with no bounds to narrow the width, binary falls back to a full float64 (8 bytes) and JSON writes the plain number. Samples include MAX_SAFE_INTEGER / MIN_SAFE_INTEGER.',
    serializeNotes: 'No bounds → no width optimization: binary uses float64 8 bytes regardless of value (getBinaryByteSizes [8,8,8]); safe-integer extremes still round-trip losslessly in both JSON and binary.',
    mutateEncoder: () => createJsonEncoder<FormatInteger>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatInteger>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<FormatInteger>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatInteger>(),
    preserveDecoder: () => createJsonDecoder<FormatInteger>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatInteger>(),
    binaryDecoder: () => createBinaryDecoder<FormatInteger>(),
    schemaEncoder: () => createJsonEncoder(RT.integer()),
    schemaDecoder: () => createJsonDecoder(RT.integer()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.integer()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.integer()),
    getTestData: () => ({values: [10, Number.MAX_SAFE_INTEGER, Number.MIN_SAFE_INTEGER]}),
    getBinaryByteSizes: () => [8, 8, 8],
  },
  number_float_8bytes: {
    title: 'FormatFloat — float64 (8 bytes)',
    description:
      'JSON + binary (de)serialization of FormatFloat (number branded {float:true}); floats encode as a full float64 (8 bytes) in binary and as the plain number in JSON. Samples include a negative and an exponent literal (1.23e10).',
    serializeNotes: 'Float values always take 8 bytes in binary (getBinaryByteSizes [8,8,8]) — no integer-width narrowing applies; both formats round-trip losslessly.',
    mutateEncoder: () => createJsonEncoder<FormatFloat>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatFloat>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<FormatFloat>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatFloat>(),
    preserveDecoder: () => createJsonDecoder<FormatFloat>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatFloat>(),
    binaryDecoder: () => createBinaryDecoder<FormatFloat>(),
    schemaEncoder: () => createJsonEncoder(RT.float()),
    schemaDecoder: () => createJsonDecoder(RT.float()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.float()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.float()),
    getTestData: () => ({values: [10.5, -3.14, 1.23e10]}),
    getBinaryByteSizes: () => [8, 8, 8],
  },
  number_ranged: {
    title: 'FormatNumber<{min:0; max:1000; integer:true}> — picks uint16 (2 bytes)',
    description:
      'JSON + binary (de)serialization of an ad-hoc ranged FormatNumber {min:0; max:1000; integer:true} (not one of the named int aliases); binary picks the narrowest unsigned width that fits [0,1000] — uint16 (2 bytes) — while JSON writes the plain number.',
    serializeNotes: 'Format-aware binary width is derived from arbitrary bounds, not just the named int formats: [0,1000] integer fits uint16, so each value packs into 2 bytes (getBinaryByteSizes [2,2,2]).',
    mutateEncoder: () => createJsonEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'clone'}),
    directEncoder: () => createJsonEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(),
    preserveDecoder: () => createJsonDecoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(),
    binaryDecoder: () => createBinaryDecoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(),
    schemaEncoder: () => createJsonEncoder(RT.number({min: 0, max: 1000, integer: true})),
    schemaDecoder: () => createJsonDecoder(RT.number({min: 0, max: 1000, integer: true})),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.number({min: 0, max: 1000, integer: true})),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.number({min: 0, max: 1000, integer: true})),
    getTestData: () => ({values: [0, 500, 1000]}),
    getBinaryByteSizes: () => [2, 2, 2],
  },
} as const satisfies Record<string, SerializationCase>;
