import type {SerializationCase} from './types.ts';
import '@mionjs/ts-go-run-types/formats';
import {createBinaryDecoder, createBinaryEncoder, createJsonDecoder, createJsonEncoder} from '@mionjs/ts-go-run-types';
import type {
  FormatNumber,
  FormatInteger,
  FormatFloat,
  FormatInt8,
  FormatInt16,
  FormatInt32,
  FormatUInt8,
  FormatUInt16,
  FormatUInt32,
} from '@mionjs/ts-go-run-types/formats';

export const NUMBER_FORMAT = {
  number_int8: {
    title: 'FormatInt8 — packs into 1 byte',
    unsafeEncoder: () => createJsonEncoder<FormatInt8>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<FormatInt8>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<FormatInt8>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<FormatInt8>(),
    safeDirectEncoder: () => createJsonEncoder<FormatInt8>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<FormatInt8>(),
    unsafeDecoder: () => createJsonDecoder<FormatInt8>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<FormatInt8>(),
    binaryDecoder: () => createBinaryDecoder<FormatInt8>(),
    getTestData: () => ({values: [-128, 0, 127]}),
    getBinaryByteSizes: () => [1, 1, 1],
  },
  number_int16: {
    title: 'FormatInt16 — packs into 2 bytes',
    unsafeEncoder: () => createJsonEncoder<FormatInt16>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<FormatInt16>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<FormatInt16>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<FormatInt16>(),
    safeDirectEncoder: () => createJsonEncoder<FormatInt16>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<FormatInt16>(),
    unsafeDecoder: () => createJsonDecoder<FormatInt16>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<FormatInt16>(),
    binaryDecoder: () => createBinaryDecoder<FormatInt16>(),
    getTestData: () => ({values: [-32768, 0, 32767]}),
    getBinaryByteSizes: () => [2, 2, 2],
  },
  number_int32: {
    title: 'FormatInt32 — packs into 4 bytes',
    unsafeEncoder: () => createJsonEncoder<FormatInt32>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<FormatInt32>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<FormatInt32>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<FormatInt32>(),
    safeDirectEncoder: () => createJsonEncoder<FormatInt32>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<FormatInt32>(),
    unsafeDecoder: () => createJsonDecoder<FormatInt32>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<FormatInt32>(),
    binaryDecoder: () => createBinaryDecoder<FormatInt32>(),
    getTestData: () => ({values: [-2147483648, 0, 2147483647]}),
    getBinaryByteSizes: () => [4, 4, 4],
  },
  number_uint8: {
    title: 'FormatUInt8 — packs into 1 byte',
    unsafeEncoder: () => createJsonEncoder<FormatUInt8>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<FormatUInt8>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<FormatUInt8>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<FormatUInt8>(),
    safeDirectEncoder: () => createJsonEncoder<FormatUInt8>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<FormatUInt8>(),
    unsafeDecoder: () => createJsonDecoder<FormatUInt8>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<FormatUInt8>(),
    binaryDecoder: () => createBinaryDecoder<FormatUInt8>(),
    getTestData: () => ({values: [0, 128, 255]}),
    getBinaryByteSizes: () => [1, 1, 1],
  },
  number_uint16: {
    title: 'FormatUInt16 — packs into 2 bytes',
    unsafeEncoder: () => createJsonEncoder<FormatUInt16>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<FormatUInt16>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<FormatUInt16>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<FormatUInt16>(),
    safeDirectEncoder: () => createJsonEncoder<FormatUInt16>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<FormatUInt16>(),
    unsafeDecoder: () => createJsonDecoder<FormatUInt16>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<FormatUInt16>(),
    binaryDecoder: () => createBinaryDecoder<FormatUInt16>(),
    getTestData: () => ({values: [0, 32768, 65535]}),
    getBinaryByteSizes: () => [2, 2, 2],
  },
  number_uint32: {
    title: 'FormatUInt32 — packs into 4 bytes',
    unsafeEncoder: () => createJsonEncoder<FormatUInt32>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<FormatUInt32>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<FormatUInt32>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<FormatUInt32>(),
    safeDirectEncoder: () => createJsonEncoder<FormatUInt32>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<FormatUInt32>(),
    unsafeDecoder: () => createJsonDecoder<FormatUInt32>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<FormatUInt32>(),
    binaryDecoder: () => createBinaryDecoder<FormatUInt32>(),
    getTestData: () => ({values: [0, 2147483648, 4294967295]}),
    getBinaryByteSizes: () => [4, 4, 4],
  },
  number_integer_8bytes: {
    title: 'FormatInteger — unbounded integer falls back to float64 (8 bytes)',
    unsafeEncoder: () => createJsonEncoder<FormatInteger>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<FormatInteger>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<FormatInteger>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<FormatInteger>(),
    safeDirectEncoder: () => createJsonEncoder<FormatInteger>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<FormatInteger>(),
    unsafeDecoder: () => createJsonDecoder<FormatInteger>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<FormatInteger>(),
    binaryDecoder: () => createBinaryDecoder<FormatInteger>(),
    getTestData: () => ({values: [10, Number.MAX_SAFE_INTEGER, Number.MIN_SAFE_INTEGER]}),
    getBinaryByteSizes: () => [8, 8, 8],
  },
  number_float_8bytes: {
    title: 'FormatFloat — float64 (8 bytes)',
    unsafeEncoder: () => createJsonEncoder<FormatFloat>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () => createJsonEncoder<FormatFloat>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () => createJsonEncoder<FormatFloat>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<FormatFloat>(),
    safeDirectEncoder: () => createJsonEncoder<FormatFloat>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<FormatFloat>(),
    unsafeDecoder: () => createJsonDecoder<FormatFloat>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<FormatFloat>(),
    binaryDecoder: () => createBinaryDecoder<FormatFloat>(),
    getTestData: () => ({values: [10.5, -3.14, 1.23e10]}),
    getBinaryByteSizes: () => [8, 8, 8],
  },
  number_ranged: {
    title: 'FormatNumber<{min:0; max:1000; integer:true}> — picks uint16 (2 bytes)',
    unsafeEncoder: () =>
      createJsonEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'mutate', stripExtras: false}),
    clonePreserveEncoder: () =>
      createJsonEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'clone', stripExtras: false}),
    mutateStripEncoder: () =>
      createJsonEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'mutate', stripExtras: true}),
    safeEncoder: () => createJsonEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(),
    safeDirectEncoder: () => createJsonEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(undefined, {strategy: 'direct'}),
    safeDecoder: () => createJsonDecoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(),
    unsafeDecoder: () => createJsonDecoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(undefined, {stripExtras: false}),
    binaryEncoder: () => createBinaryEncoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(),
    binaryDecoder: () => createBinaryDecoder<FormatNumber<{min: 0; max: 1000; integer: true}>>(),
    getTestData: () => ({values: [0, 500, 1000]}),
    getBinaryByteSizes: () => [2, 2, 2],
  },
} as const satisfies Record<string, SerializationCase>;
