import type {SerializationCase} from './types.ts';
import * as RT from '@mionjs/ts-go-run-types/schema';
import '@mionjs/ts-go-run-types/formats';
import {createBinaryDecoder, createBinaryEncoder, createJsonDecoder, createJsonEncoder} from '@mionjs/ts-go-run-types';
import type {FormatString, FormatAlpha, FormatUUIDv4, FormatStringDate, FormatEmail} from '@mionjs/ts-go-run-types/formats';

const V4 = '9f1b8c2e-3d4a-4b5c-8d6e-1f2a3b4c5d6e';

export const STRING_FORMAT = {
  string_maxLength: {
    title: 'FormatString<{maxLength: 5}>',
    mutateEncoder: () => createJsonEncoder<FormatString<{maxLength: 5}>>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatString<{maxLength: 5}>>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<FormatString<{maxLength: 5}>>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<FormatString<{maxLength: 5}>>(),
    directEncoder: () => createJsonEncoder<FormatString<{maxLength: 5}>>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatString<{maxLength: 5}>>(),
    preserveDecoder: () => createJsonDecoder<FormatString<{maxLength: 5}>>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatString<{maxLength: 5}>>(),
    binaryDecoder: () => createBinaryDecoder<FormatString<{maxLength: 5}>>(),
    schemaEncoder: () => createJsonEncoder(RT.string({maxLength: 5})),
    schemaDecoder: () => createJsonDecoder(RT.string({maxLength: 5})),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.string({maxLength: 5})),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.string({maxLength: 5})),
    getTestData: () => ({values: ['', 'hello', 'abc']}),
  },
  uuidv4: {
    title: 'FormatUUIDv4',
    mutateEncoder: () => createJsonEncoder<FormatUUIDv4>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatUUIDv4>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<FormatUUIDv4>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<FormatUUIDv4>(),
    directEncoder: () => createJsonEncoder<FormatUUIDv4>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatUUIDv4>(),
    preserveDecoder: () => createJsonDecoder<FormatUUIDv4>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatUUIDv4>(),
    binaryDecoder: () => createBinaryDecoder<FormatUUIDv4>(),
    schemaEncoder: () => createJsonEncoder(RT.uuidv4()),
    schemaDecoder: () => createJsonDecoder(RT.uuidv4()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.uuidv4()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.uuidv4()),
    getTestData: () => ({values: [V4]}),
  },
  date: {
    title: 'FormatStringDate',
    mutateEncoder: () => createJsonEncoder<FormatStringDate>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatStringDate>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<FormatStringDate>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<FormatStringDate>(),
    directEncoder: () => createJsonEncoder<FormatStringDate>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatStringDate>(),
    preserveDecoder: () => createJsonDecoder<FormatStringDate>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatStringDate>(),
    binaryDecoder: () => createBinaryDecoder<FormatStringDate>(),
    schemaEncoder: () => createJsonEncoder(RT.stringDate()),
    schemaDecoder: () => createJsonDecoder(RT.stringDate()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.stringDate()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.stringDate()),
    getTestData: () => ({values: ['2024-02-29', '2026-05-28', '0001-01-01']}),
  },
  email: {
    title: 'FormatEmail',
    mutateEncoder: () => createJsonEncoder<FormatEmail>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatEmail>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<FormatEmail>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<FormatEmail>(),
    directEncoder: () => createJsonEncoder<FormatEmail>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatEmail>(),
    preserveDecoder: () => createJsonDecoder<FormatEmail>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatEmail>(),
    binaryDecoder: () => createBinaryDecoder<FormatEmail>(),
    schemaEncoder: () => createJsonEncoder(RT.email()),
    schemaDecoder: () => createJsonDecoder(RT.email()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.email()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.email()),
    getTestData: () => ({values: ['john@example.com', 'jane.doe@mion.io']}),
  },
  alpha: {
    title: 'FormatAlpha',
    mutateEncoder: () => createJsonEncoder<FormatAlpha>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatAlpha>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<FormatAlpha>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<FormatAlpha>(),
    directEncoder: () => createJsonEncoder<FormatAlpha>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatAlpha>(),
    preserveDecoder: () => createJsonDecoder<FormatAlpha>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatAlpha>(),
    binaryDecoder: () => createBinaryDecoder<FormatAlpha>(),
    schemaEncoder: () => createJsonEncoder(RT.alpha()),
    schemaDecoder: () => createJsonDecoder(RT.alpha()),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.alpha()),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.alpha()),
    getTestData: () => ({values: ['Hello', 'abcXYZ']}),
  },
  object_with_formats: {
    title: 'object with format-branded fields {id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}',
    mutateEncoder: () =>
      createJsonEncoder<{id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () =>
      createJsonEncoder<{id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () =>
      createJsonEncoder<{id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<{id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}>(),
    directEncoder: () =>
      createJsonEncoder<{id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<{id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}>(),
    preserveDecoder: () =>
      createJsonDecoder<{id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<{id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}>(),
    binaryDecoder: () => createBinaryDecoder<{id: FormatUUIDv4; name: FormatString<{maxLength: 20}>}>(),
    schemaEncoder: () => createJsonEncoder(RT.object({id: RT.uuidv4(), name: RT.string({maxLength: 20})})),
    schemaDecoder: () => createJsonDecoder(RT.object({id: RT.uuidv4(), name: RT.string({maxLength: 20})})),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.object({id: RT.uuidv4(), name: RT.string({maxLength: 20})})),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.object({id: RT.uuidv4(), name: RT.string({maxLength: 20})})),
    getTestData: () => ({values: [{id: V4, name: 'alice'}]}),
  },
  email_array: {
    title: 'array of FormatEmail',
    mutateEncoder: () => createJsonEncoder<FormatEmail[]>(undefined, {strategy: 'mutate'}),
    cloneEncoder: () => createJsonEncoder<FormatEmail[]>(undefined, {strategy: 'clone'}),
    stripMutateEncoder: () => createJsonEncoder<FormatEmail[]>(undefined, {strategy: 'stripMutate'}),
    stripCloneEncoder: () => createJsonEncoder<FormatEmail[]>(),
    directEncoder: () => createJsonEncoder<FormatEmail[]>(undefined, {strategy: 'direct'}),
    stripDecoder: () => createJsonDecoder<FormatEmail[]>(),
    preserveDecoder: () => createJsonDecoder<FormatEmail[]>(undefined, {strategy: 'preserve'}),
    binaryEncoder: () => createBinaryEncoder<FormatEmail[]>(),
    binaryDecoder: () => createBinaryDecoder<FormatEmail[]>(),
    schemaEncoder: () => createJsonEncoder(RT.array(RT.email())),
    schemaDecoder: () => createJsonDecoder(RT.array(RT.email())),
    schemaBinaryEncoder: () => createBinaryEncoder(RT.array(RT.email())),
    schemaBinaryDecoder: () => createBinaryDecoder(RT.array(RT.email())),
    getTestData: () => ({values: [['john@example.com', 'jane.doe@mion.io']]}),
  },
} as const satisfies Record<string, SerializationCase>;
