package emit

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/mionkit/ts-run-types/internal/constants"
	"github.com/mionkit/ts-run-types/internal/protocol"
)

// RunTypesModule writes the runtime artifact: a self-contained JS module that
// declares every cached type as a top-level `export const <prefix><hash>`
// built via a single universal factory function, then a footer block that
// resolves refs by direct assignment so consumers receive a fully-knotted
// reflection RunType graph.
//
// The factory `_T` returns one object literal whose shape contains every key
// any node will ever carry — header scalars come from positional args, every
// ref slot is hardcoded to `null`. Call sites pass `u` (alias for `undefined`)
// for slots that don't apply; trailing `u`s are trimmed so calls stay short.
// Every emitted node therefore shares one V8 hidden class, and the footer's
// `t_X.child = t_Y;` patches land on a pre-existing slot.
//
// Footer special-cases (unchanged from the previous emitter):
//   - Literal bigint  → `t.literal = BigInt("…")`
//   - Literal symbol  → `t.literal = Symbol("…")`
//   - Literal regexp  → `t.literal = /source/flags`
//   - Class with ClassRef.Builtin → `t.classType = globalThis.<Name>`
func RunTypesModule(writer io.Writer, dump protocol.Dump) error {
	settings := constants.CacheModules["runTypes"]
	buffered := &bufWriter{writer: writer}
	buffered.line("// Code generated by ts-go-run-types. DO NOT EDIT.")
	buffered.line("// Source: reflection-shape runtime cache for mion runtypes.")
	buffered.line("")
	for _, line := range factoryPreambleLines {
		buffered.line(line)
	}
	buffered.line("")

	for _, runType := range dump.RunTypes {
		if runType == nil {
			continue
		}
		args := renderFactoryArgs(runType)
		buffered.line(fmt.Sprintf("export const %s = _T(%s);", varName(settings, runType.ID), strings.Join(args, ", ")))
	}

	buffered.line("")
	buffered.line("// --- knot refs and runtime values ---")
	for _, runType := range dump.RunTypes {
		if runType == nil {
			continue
		}
		writeFooter(buffered, settings, runType)
	}

	return buffered.err
}

// factoryPreambleLines holds the `const u = undefined;` alias and the
// universal `_T` factory. The factory is a pure single-expression arrow
// returning one object literal whose own-key set is identical for every
// node — that's the property V8 uses to assign a stable hidden class. Param
// order matches the canonical RunType field order; reserved-word JS
// property names are kept as runtime keys by aliasing the Go param to
// `abstract_` / `static_` / `default_` / `enum_` and renaming inline in
// the returned literal.
var factoryPreambleLines = []string{
	"const u = undefined;",
	"const _T = (id, kind, typeName, name, literal,",
	"            optional, readonly, abstract_, static_, visibility,",
	"            isSafePropName, position, inlined, flags,",
	"            description, default_, enum_, values) => ({",
	"  id, kind, typeName, name, literal,",
	"  optional, readonly,",
	"  abstract: abstract_, static: static_,",
	"  visibility, isSafePropName, position, inlined, flags,",
	"  description, default: default_, enum: enum_, values,",
	"  child: null, index: null, return: null, indexType: null,",
	"  parameters: null, children: null,",
	"  safeUnionChildren: null, unionDiscriminators: null,",
	"  decorators: null, typeArguments: null,",
	"  arguments: null, extendsArguments: null,",
	"  implements: null, extends: null,",
	"  classType: null,",
	"});",
}

// renderFactoryArgs builds the positional-arg slice for one `_T(…)` call,
// then trims trailing `u` entries so the call stays compact. The first two
// args (`id`, `kind`) are always present.
func renderFactoryArgs(runType *protocol.RunType) []string {
	args := []string{
		strconv.Quote(runType.ID),       // 0: id
		strconv.Itoa(int(runType.Kind)), // 1: kind
		stringArg(runType.TypeName),     // 2: typeName
		stringArg(runType.Name),         // 3: name
		literalArg(runType),             // 4: literal
		boolArg(runType.Optional),       // 5: optional
		boolArg(runType.Readonly),       // 6: readonly
		boolArg(runType.Abstract),       // 7: abstract
		boolArg(runType.Static),         // 8: static
		intPtrArg(runType.Visibility),   // 9: visibility
		boolArg(runType.IsSafePropName), // 10: isSafePropName
		intPtrArg(runType.Position),     // 11: position
		boolArg(runType.Inlined),        // 12: inlined
		flagsArg(runType.Flags),         // 13: flags
		stringArg(runType.Description),  // 14: description
		jsonArg(runType.Default),        // 15: default
		enumArg(runType.Enum),           // 16: enum
		valuesArg(runType.Values),       // 17: values
	}
	return trimTrailingUndefined(args)
}

// stringArg returns the JS source for a string field — `u` when empty,
// otherwise a quoted JS string literal.
func stringArg(value string) string {
	if value == "" {
		return "u"
	}
	return strconv.Quote(value)
}

// boolArg returns `"true"` when set, otherwise `"u"`. False is treated as
// "absent" to keep the call site compact; the own-key still exists on the
// returned object because the factory's literal declares it.
func boolArg(value bool) string {
	if value {
		return "true"
	}
	return "u"
}

// intPtrArg renders a *int as its decimal integer or `u` when nil. The
// pointer indirection matters — `Position == 0` is a meaningful value and
// must round-trip as `"0"`, not `"u"`.
func intPtrArg(value *int) string {
	if value == nil {
		return "u"
	}
	return strconv.Itoa(*value)
}

// literalArg renders the `literal` slot. Footer-special literals (bigint,
// symbol, regexp) are emitted by writeFooter, so the factory arg stays `u`
// for those — the footer assignment then patches the literal in place.
func literalArg(runType *protocol.RunType) string {
	if runType.Literal == nil {
		return "u"
	}
	if isFooterLiteral(runType) {
		return "u"
	}
	return mustJSON(runType.Literal)
}

// jsonArg returns `u` for nil, otherwise the JSON encoding of the value.
func jsonArg(value any) string {
	if value == nil {
		return "u"
	}
	return mustJSON(value)
}

// flagsArg renders a []string as a JS array literal or `u` when empty.
func flagsArg(flags []string) string {
	if len(flags) == 0 {
		return "u"
	}
	return mustJSON(flags)
}

// enumArg renders an enum map or `u` when empty/nil.
func enumArg(enum map[string]any) string {
	if len(enum) == 0 {
		return "u"
	}
	return mustJSON(enum)
}

// valuesArg renders a []any or `u` when empty.
func valuesArg(values []any) string {
	if len(values) == 0 {
		return "u"
	}
	return mustJSON(values)
}

// trimTrailingUndefined drops trailing `"u"` entries from the arg slice so
// `_T(…)` calls stay compact. The first two slots (id, kind) are always
// emitted; the minimum slice length is therefore 2.
func trimTrailingUndefined(args []string) []string {
	end := len(args)
	for end > 2 && args[end-1] == "u" {
		end--
	}
	return args[:end]
}

// varName turns a hash id into a JS const identifier by prepending the
// module's configured prefix. Hashes (and the `x_*` synthetic ids) are
// already valid JS identifiers, so no per-character sanitisation is needed.
func varName(settings constants.CacheModuleSettings, id string) string {
	return settings.VarPrefix + id
}

// isFooterLiteral reports whether runType.Literal needs special construction
// in the footer (bigint / symbol / regexp) rather than inline JSON.
func isFooterLiteral(runType *protocol.RunType) bool {
	if runType.Literal == nil {
		return false
	}
	for _, flag := range runType.Flags {
		if flag == "bigint" || flag == "symbol" {
			return true
		}
	}
	if literalMap, ok := runType.Literal.(map[string]any); ok {
		if _, hasRegexp := literalMap["regexp"]; hasRegexp {
			return true
		}
	}
	return false
}

// writeFooter fills runType's reference-bearing fields and runtime-special values.
func writeFooter(buffered *bufWriter, settings constants.CacheModuleSettings, runType *protocol.RunType) {
	name := varName(settings, runType.ID)
	if runType.Child != nil {
		buffered.line(fmt.Sprintf("%s.child = %s;", name, derefExpr(settings, runType.Child)))
	}
	if runType.Index != nil {
		buffered.line(fmt.Sprintf("%s.index = %s;", name, derefExpr(settings, runType.Index)))
	}
	if runType.Return != nil {
		buffered.line(fmt.Sprintf("%s.return = %s;", name, derefExpr(settings, runType.Return)))
	}
	if runType.IndexT != nil {
		buffered.line(fmt.Sprintf("%s.indexType = %s;", name, derefExpr(settings, runType.IndexT)))
	}
	if len(runType.Parameters) > 0 {
		buffered.line(fmt.Sprintf("%s.parameters = [%s];", name, joinRefs(settings, runType.Parameters)))
	}
	if len(runType.Children) > 0 {
		buffered.line(fmt.Sprintf("%s.children = [%s];", name, joinRefs(settings, runType.Children)))
	}
	// safeUnionChildren — same ref objects as Children, reordered so
	// superset shapes precede their subset equivalents. Emitted as a
	// parallel array; consumers derive per-member safe position via
	// `safeUnionChildren.indexOf(member)`.
	if len(runType.SafeUnionChildren) > 0 {
		buffered.line(fmt.Sprintf("%s.safeUnionChildren = [%s];", name, joinRefs(settings, runType.SafeUnionChildren)))
	}
	// unionDiscriminators — parallel to safeUnionChildren; entry i is a
	// ref to the discriminator property within safeUnionChildren[i].
	// Non-object slots stay null/undefined; the slice is emitted only
	// when at least one slot is populated.
	if len(runType.UnionDiscriminators) > 0 {
		buffered.line(fmt.Sprintf("%s.unionDiscriminators = [%s];", name, joinRefs(settings, runType.UnionDiscriminators)))
	}
	// decorators — surviving object-literal types from a collapsed
	// `primitive & {brand}` intersection.
	if len(runType.Decorators) > 0 {
		buffered.line(fmt.Sprintf("%s.decorators = [%s];", name, joinRefs(settings, runType.Decorators)))
	}
	if len(runType.TypeArguments) > 0 {
		buffered.line(fmt.Sprintf("%s.typeArguments = [%s];", name, joinRefs(settings, runType.TypeArguments)))
	}
	if len(runType.Arguments) > 0 {
		buffered.line(fmt.Sprintf("%s.arguments = [%s];", name, joinRefs(settings, runType.Arguments)))
	}
	if len(runType.ExtendsArguments) > 0 {
		buffered.line(fmt.Sprintf("%s.extendsArguments = [%s];", name, joinRefs(settings, runType.ExtendsArguments)))
	}
	if len(runType.Implements) > 0 {
		buffered.line(fmt.Sprintf("%s.implements = [%s];", name, joinRefs(settings, runType.Implements)))
	}
	if len(runType.Extends) > 0 {
		buffered.line(fmt.Sprintf("%s.extends = [%s];", name, joinRefs(settings, runType.Extends)))
	}

	// classType — built-in constructors looked up on globalThis so the
	// generated module needs zero runtime imports.
	if runType.ClassRef != nil && runType.ClassRef.Builtin != "" {
		buffered.line(fmt.Sprintf("%s.classType = globalThis.%s;", name, runType.ClassRef.Builtin))
	}

	// Footer-only literals.
	if isFooterLiteral(runType) {
		buffered.line(fmt.Sprintf("%s.literal = %s;", name, footerLiteralExpr(runType)))
	}
}

// footerLiteralExpr renders a runtime-special literal as a JS expression.
func footerLiteralExpr(runType *protocol.RunType) string {
	for _, flag := range runType.Flags {
		if flag == "bigint" {
			literalString, _ := runType.Literal.(string)
			return fmt.Sprintf("BigInt(%q)", literalString)
		}
		if flag == "symbol" {
			if literalMap, ok := runType.Literal.(map[string]any); ok {
				if name, ok := literalMap["symbol"].(string); ok {
					return fmt.Sprintf("Symbol(%q)", name)
				}
			}
			return "Symbol()"
		}
	}
	if literalMap, ok := runType.Literal.(map[string]any); ok {
		if regexpRaw, ok := literalMap["regexp"].(map[string]any); ok {
			source, _ := regexpRaw["source"].(string)
			flags, _ := regexpRaw["flags"].(string)
			return fmt.Sprintf("/%s/%s", source, flags)
		}
	}
	return mustJSON(runType.Literal)
}

// derefExpr renders a single child slot. Refs become bare const names;
// inline Types become JSON literals.
func derefExpr(settings constants.CacheModuleSettings, runType *protocol.RunType) string {
	if runType == nil {
		return "undefined"
	}
	if runType.Kind == protocol.KindRef {
		return varName(settings, runType.ID)
	}
	return mustJSON(runType)
}

func joinRefs(settings constants.CacheModuleSettings, runTypes []*protocol.RunType) string {
	parts := make([]string, len(runTypes))
	for i, runType := range runTypes {
		parts[i] = derefExpr(settings, runType)
	}
	return strings.Join(parts, ", ")
}

func mustJSON(value any) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return fmt.Sprintf("/* json err: %v */ undefined", err)
	}
	return string(encoded)
}

type bufWriter struct {
	writer io.Writer
	err    error
}

func (buffered *bufWriter) line(line string) {
	if buffered.err != nil {
		return
	}
	_, buffered.err = io.WriteString(buffered.writer, line+"\n")
}
