package emit

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"

	"github.com/mionkit/ts-run-types/internal/constants"
	"github.com/mionkit/ts-run-types/internal/protocol"
)

// RunTypesModule writes the runtime artifact: a self-contained JS module that
// declares every cached type as a top-level `export const <prefix><hash>`
// built via a single universal factory function, then a footer block that
// resolves refs by direct assignment so consumers receive a fully-knotted
// reflection RunType graph.
//
// The factory `RT` returns one object literal whose shape contains every key
// any node will ever carry — header scalars come from positional args, every
// ref slot is initialised to `u` (alias for `undefined`). Call sites pass `u`
// for header slots that don't apply; trailing `u`s are trimmed so calls stay
// short. Every emitted node therefore shares one V8 hidden class (hidden
// classes are shape-determined, not value-determined, so `u`/`undefined` and
// `null` would yield the same Map — `u` is preferred because `JSON.stringify`
// drops undefined slots, shrinking any downstream serialisation a consumer
// does, and the source-text byte cost matches `null` thanks to the alias).
// The footer's `t_X.child = t_Y;` patches land on a pre-existing slot.
//
// Footer special-cases (unchanged from the previous emitter):
//   - Literal bigint  → `t.literal = BigInt("…")`
//   - Literal symbol  → `t.literal = Symbol("…")`
//   - Literal regexp  → `t.literal = /source/flags`
//   - Class with ClassRef.Builtin → `t.classType = globalThis.<Name>`
func RunTypesModule(writer io.Writer, dump protocol.Dump) error {
	settings := constants.CacheModules["runTypes"]
	buffered := &bufWriter{writer: writer}
	buffered.line("// Code generated by ts-go-run-types. DO NOT EDIT.")
	buffered.line("// Source: reflection-shape runtime cache for mion runtypes.")
	buffered.line("")
	for _, line := range factoryPreambleLines {
		buffered.line(line)
	}
	buffered.line("")

	for _, runType := range dump.RunTypes {
		if runType == nil {
			continue
		}
		args := renderFactoryArgs(runType)
		buffered.line(fmt.Sprintf("export const %s = RT(%s);", varName(settings, runType.ID), strings.Join(args, ",")))
	}

	buffered.line("")
	buffered.line("// --- knot refs and runtime values ---")
	for _, runType := range dump.RunTypes {
		if runType == nil {
			continue
		}
		writeFooter(buffered, settings, runType)
	}

	return buffered.err
}

// factoryPreambleLines holds the `const u = undefined;` alias and the
// universal `RT` factory. The factory is a pure single-expression arrow
// returning one object literal whose own-key set is identical for every
// node — that's the property V8 uses to assign a stable hidden class. Param
// order matches the canonical RunType field order. All factory params are
// plain identifiers (no reserved words) because the protocol exposes the
// would-be-reserved fields as `isAbstract` / `isStatic` / `defaultVal` /
// `enumVal`, so every key can use ES shorthand without aliasing.
var factoryPreambleLines = []string{
	"const u = undefined;",
	"const RT = (id, kind, typeName, name, literal,",
	"            optional, readonly, isAbstract, isStatic, visibility,",
	"            isSafeName, position, inlined, flags,",
	"            description, defaultVal, enumVal, values) => ({",
	"  id, kind, typeName, name, literal,",
	"  optional, readonly, isAbstract, isStatic,",
	"  visibility, isSafeName, position, inlined, flags,",
	"  description, defaultVal, enumVal, values,",
	"  child: u, index: u, return: u, indexType: u,",
	"  parameters: u, children: u,",
	"  safeUnionChildren: u, unionDiscriminators: u,",
	"  decorators: u, typeArguments: u,",
	"  arguments: u, extendsArguments: u,",
	"  implements: u, extends: u,",
	"  classType: u,",
	"});",
}

// renderFactoryArgs builds the positional-arg slice for one `RT(…)` call,
// then trims trailing `u` entries so the call stays compact. The first two
// args (`id`, `kind`) are always present.
func renderFactoryArgs(runType *protocol.RunType) []string {
	args := []string{
		quoteJS(runType.ID),             // 0: id
		strconv.Itoa(int(runType.Kind)), // 1: kind
		stringArg(runType.TypeName),     // 2: typeName
		stringArg(runType.Name),         // 3: name
		literalArg(runType),             // 4: literal
		boolArg(runType.Optional),       // 5: optional
		boolArg(runType.Readonly),       // 6: readonly
		boolArg(runType.IsAbstract),     // 7: isAbstract
		boolArg(runType.IsStatic),       // 8: isStatic
		intPtrArg(runType.Visibility),   // 9: visibility
		boolArg(runType.IsSafeName), // 10: isSafeName
		intPtrArg(runType.Position),     // 11: position
		boolArg(runType.Inlined),        // 12: inlined
		flagsArg(runType.Flags),         // 13: flags
		stringArg(runType.Description),  // 14: description
		jsonArg(runType.DefaultVal),     // 15: defaultVal
		enumArg(runType.EnumVal),        // 16: enumVal
		valuesArg(runType.Values),       // 17: values
	}
	return trimTrailingUndefined(args)
}

// stringArg returns the JS source for a string field — `u` when empty,
// otherwise a single-quoted JS string literal (see quoteJS for rationale).
func stringArg(value string) string {
	if value == "" {
		return "u"
	}
	return quoteJS(value)
}

// boolArg returns `"true"` when set, otherwise `"u"`. False is treated as
// "absent" to keep the call site compact; the own-key still exists on the
// returned object because the factory's literal declares it.
func boolArg(value bool) string {
	if value {
		return "true"
	}
	return "u"
}

// intPtrArg renders a *int as its decimal integer or `u` when nil. The
// pointer indirection matters — `Position == 0` is a meaningful value and
// must round-trip as `"0"`, not `"u"`.
func intPtrArg(value *int) string {
	if value == nil {
		return "u"
	}
	return strconv.Itoa(*value)
}

// literalArg renders the `literal` slot. Footer-special literals (bigint,
// symbol, regexp) are emitted by writeFooter, so the factory arg stays `u`
// for those — the footer assignment then patches the literal in place.
func literalArg(runType *protocol.RunType) string {
	if runType.Literal == nil {
		return "u"
	}
	if isFooterLiteral(runType) {
		return "u"
	}
	return mustJSLiteral(runType.Literal)
}

// jsonArg returns `u` for nil, otherwise the JS-literal encoding of value.
func jsonArg(value any) string {
	if value == nil {
		return "u"
	}
	return mustJSLiteral(value)
}

// flagsArg renders a []string as a JS array literal or `u` when empty.
func flagsArg(flags []string) string {
	if len(flags) == 0 {
		return "u"
	}
	return mustJSLiteral(flags)
}

// enumArg renders an enum map or `u` when empty/nil.
func enumArg(enum map[string]any) string {
	if len(enum) == 0 {
		return "u"
	}
	return mustJSLiteral(enum)
}

// valuesArg renders a []any or `u` when empty.
func valuesArg(values []any) string {
	if len(values) == 0 {
		return "u"
	}
	return mustJSLiteral(values)
}

// trimTrailingUndefined drops trailing `"u"` entries from the arg slice so
// `RT(…)` calls stay compact. The first two slots (id, kind) are always
// emitted; the minimum slice length is therefore 2.
func trimTrailingUndefined(args []string) []string {
	end := len(args)
	for end > 2 && args[end-1] == "u" {
		end--
	}
	return args[:end]
}

// varName turns a hash id into a JS const identifier by prepending the
// module's configured prefix. Hashes (and the `x_*` synthetic ids) are
// already valid JS identifiers, so no per-character sanitisation is needed.
func varName(settings constants.CacheModuleSettings, id string) string {
	return settings.VarPrefix + id
}

// isFooterLiteral reports whether runType.Literal needs special construction
// in the footer (bigint / symbol / regexp) rather than inline JSON.
func isFooterLiteral(runType *protocol.RunType) bool {
	if runType.Literal == nil {
		return false
	}
	for _, flag := range runType.Flags {
		if flag == "bigint" || flag == "symbol" {
			return true
		}
	}
	if literalMap, ok := runType.Literal.(map[string]any); ok {
		if _, hasRegexp := literalMap["regexp"]; hasRegexp {
			return true
		}
	}
	return false
}

// writeFooter fills runType's reference-bearing fields and runtime-special values.
func writeFooter(buffered *bufWriter, settings constants.CacheModuleSettings, runType *protocol.RunType) {
	name := varName(settings, runType.ID)
	if runType.Child != nil {
		buffered.line(fmt.Sprintf("%s.child = %s;", name, derefExpr(settings, runType.Child)))
	}
	if runType.Index != nil {
		buffered.line(fmt.Sprintf("%s.index = %s;", name, derefExpr(settings, runType.Index)))
	}
	if runType.Return != nil {
		buffered.line(fmt.Sprintf("%s.return = %s;", name, derefExpr(settings, runType.Return)))
	}
	if runType.IndexT != nil {
		buffered.line(fmt.Sprintf("%s.indexType = %s;", name, derefExpr(settings, runType.IndexT)))
	}
	if len(runType.Parameters) > 0 {
		buffered.line(fmt.Sprintf("%s.parameters = [%s];", name, joinRefs(settings, runType.Parameters)))
	}
	if len(runType.Children) > 0 {
		buffered.line(fmt.Sprintf("%s.children = [%s];", name, joinRefs(settings, runType.Children)))
	}
	// safeUnionChildren — same ref objects as Children, reordered so
	// superset shapes precede their subset equivalents. Emitted as a
	// parallel array; consumers derive per-member safe position via
	// `safeUnionChildren.indexOf(member)`.
	if len(runType.SafeUnionChildren) > 0 {
		buffered.line(fmt.Sprintf("%s.safeUnionChildren = [%s];", name, joinRefs(settings, runType.SafeUnionChildren)))
	}
	// unionDiscriminators — parallel to safeUnionChildren; entry i is a
	// ref to the discriminator property within safeUnionChildren[i].
	// Non-object slots stay null/undefined; the slice is emitted only
	// when at least one slot is populated.
	if len(runType.UnionDiscriminators) > 0 {
		buffered.line(fmt.Sprintf("%s.unionDiscriminators = [%s];", name, joinRefs(settings, runType.UnionDiscriminators)))
	}
	// decorators — surviving object-literal types from a collapsed
	// `primitive & {brand}` intersection.
	if len(runType.Decorators) > 0 {
		buffered.line(fmt.Sprintf("%s.decorators = [%s];", name, joinRefs(settings, runType.Decorators)))
	}
	if len(runType.TypeArguments) > 0 {
		buffered.line(fmt.Sprintf("%s.typeArguments = [%s];", name, joinRefs(settings, runType.TypeArguments)))
	}
	if len(runType.Arguments) > 0 {
		buffered.line(fmt.Sprintf("%s.arguments = [%s];", name, joinRefs(settings, runType.Arguments)))
	}
	if len(runType.ExtendsArguments) > 0 {
		buffered.line(fmt.Sprintf("%s.extendsArguments = [%s];", name, joinRefs(settings, runType.ExtendsArguments)))
	}
	if len(runType.Implements) > 0 {
		buffered.line(fmt.Sprintf("%s.implements = [%s];", name, joinRefs(settings, runType.Implements)))
	}
	if len(runType.Extends) > 0 {
		buffered.line(fmt.Sprintf("%s.extends = [%s];", name, joinRefs(settings, runType.Extends)))
	}

	// classType — built-in constructors looked up on globalThis so the
	// generated module needs zero runtime imports.
	if runType.ClassRef != nil && runType.ClassRef.Builtin != "" {
		buffered.line(fmt.Sprintf("%s.classType = globalThis.%s;", name, runType.ClassRef.Builtin))
	}

	// Footer-only literals.
	if isFooterLiteral(runType) {
		buffered.line(fmt.Sprintf("%s.literal = %s;", name, footerLiteralExpr(runType)))
	}
}

// footerLiteralExpr renders a runtime-special literal as a JS expression.
func footerLiteralExpr(runType *protocol.RunType) string {
	for _, flag := range runType.Flags {
		if flag == "bigint" {
			literalString, _ := runType.Literal.(string)
			return "BigInt(" + quoteJS(literalString) + ")"
		}
		if flag == "symbol" {
			if literalMap, ok := runType.Literal.(map[string]any); ok {
				if name, ok := literalMap["symbol"].(string); ok {
					return "Symbol(" + quoteJS(name) + ")"
				}
			}
			return "Symbol()"
		}
	}
	if literalMap, ok := runType.Literal.(map[string]any); ok {
		if regexpRaw, ok := literalMap["regexp"].(map[string]any); ok {
			source, _ := regexpRaw["source"].(string)
			flags, _ := regexpRaw["flags"].(string)
			return fmt.Sprintf("/%s/%s", source, flags)
		}
	}
	return mustJSLiteral(runType.Literal)
}

// derefExpr renders a single child slot. Refs become bare const names;
// inline (non-ref) Types are round-tripped through JSON to land in the
// any-tree shape that mustJSLiteral understands, so the emitted struct
// participates in the same single-quoted output as the rest of the module.
// This is a rare path — most child slots are KindRef → bare var name.
func derefExpr(settings constants.CacheModuleSettings, runType *protocol.RunType) string {
	if runType == nil {
		return "undefined"
	}
	if runType.Kind == protocol.KindRef {
		return varName(settings, runType.ID)
	}
	encoded, err := json.Marshal(runType)
	if err != nil {
		return fmt.Sprintf("/* json err: %v */ undefined", err)
	}
	var generic any
	if err := json.Unmarshal(encoded, &generic); err != nil {
		return fmt.Sprintf("/* json err: %v */ undefined", err)
	}
	return mustJSLiteral(generic)
}

func joinRefs(settings constants.CacheModuleSettings, runTypes []*protocol.RunType) string {
	parts := make([]string, len(runTypes))
	for i, runType := range runTypes {
		parts[i] = derefExpr(settings, runType)
	}
	return strings.Join(parts, ", ")
}

// quoteJS renders a Go string as a JS source-level **single-quoted** string
// literal. Single quotes are preferred over `strconv.Quote`'s double quotes
// because the emitted module body is shipped over the resolver protocol as
// a JSON-encoded `cacheSource` string — every `"` inside the JS source then
// costs an extra escape byte (`\"`) on the wire. Single-quoting keeps the
// JSON envelope unescaped for the overwhelmingly common case of JS strings
// that contain no apostrophes (hash ids, kind names, property names, …).
//
// The implementation piggybacks on `strconv.Quote` so unicode/control-char
// escaping stays correct, then swaps the wrapping and the two quote-class
// escapes: `\"` is no longer needed inside a single-quoted JS string, and
// any literal `'` must be `\'`.
func quoteJS(value string) string {
	quoted := strconv.Quote(value)
	inner := quoted[1 : len(quoted)-1]
	inner = strings.ReplaceAll(inner, `\"`, `"`)
	inner = strings.ReplaceAll(inner, `'`, `\'`)
	return "'" + inner + "'"
}

// mustJSLiteral renders an arbitrary value as a JS source-level literal.
// Same wire-efficiency motivation as `quoteJS`: every string the value
// contains (including object keys) is single-quoted. Numbers, booleans and
// null serialize identically to JSON. Unrecognised types fall back to
// `json.Marshal` — that branch produces valid JS but with double-quoted
// strings inside, so prefer extending the type switch when a new shape
// appears in the dump.
func mustJSLiteral(value any) string {
	var builder strings.Builder
	writeJSLiteral(&builder, value)
	return builder.String()
}

func writeJSLiteral(builder *strings.Builder, value any) {
	switch typed := value.(type) {
	case nil:
		builder.WriteString("null")
	case bool:
		if typed {
			builder.WriteString("true")
		} else {
			builder.WriteString("false")
		}
	case string:
		builder.WriteString(quoteJS(typed))
	case []any:
		builder.WriteByte('[')
		for i, item := range typed {
			if i > 0 {
				builder.WriteByte(',')
			}
			writeJSLiteral(builder, item)
		}
		builder.WriteByte(']')
	case []string:
		builder.WriteByte('[')
		for i, item := range typed {
			if i > 0 {
				builder.WriteByte(',')
			}
			builder.WriteString(quoteJS(item))
		}
		builder.WriteByte(']')
	case map[string]any:
		// Sort keys for deterministic output (matches encoding/json behavior).
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		builder.WriteByte('{')
		for i, key := range keys {
			if i > 0 {
				builder.WriteByte(',')
			}
			builder.WriteString(quoteJS(key))
			builder.WriteByte(':')
			writeJSLiteral(builder, typed[key])
		}
		builder.WriteByte('}')
	default:
		// Numeric primitives and other JSON-safe types fall back to JSON.
		encoded, err := json.Marshal(typed)
		if err != nil {
			fmt.Fprintf(builder, "/* json err: %v */ undefined", err)
			return
		}
		builder.Write(encoded)
	}
}

type bufWriter struct {
	writer io.Writer
	err    error
}

func (buffered *bufWriter) line(line string) {
	if buffered.err != nil {
		return
	}
	_, buffered.err = io.WriteString(buffered.writer, line+"\n")
}
