package emit

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/mionkit/ts-run-types/internal/constants"
	"github.com/mionkit/ts-run-types/internal/protocol"
)

// RunTypesModule writes the runtime artifact: a self-contained JS module that
// declares every cached type as a top-level `export const <prefix><hash>`,
// then a footer block that resolves refs and wires up `parent` by direct
// assignment so consumers receive a fully-knotted reflection `RunType` graph.
//
// The variable prefix and module name are read from the
// `CacheModules["runTypes"]` settings entry, so adding a sibling module is a
// matter of adding another entry rather than touching the renderer.
//
// Output is plain JS (no TS annotations) so Vite/oxc / node-vm can consume
// it without a TS loader. Callers that want a .ts file just rename it.
//
// Footer special-cases:
//   - Literal bigint  → `t.literal = BigInt("…")`
//   - Literal symbol  → `t.literal = Symbol("…")`
//   - Literal regexp  → `t.literal = /source/flags`
//   - Class with ClassRef.Builtin → `t.classType = globalThis.<Name>`
func RunTypesModule(writer io.Writer, dump protocol.Dump) error {
	settings := constants.CacheModules["runTypes"]
	buffered := &bufWriter{writer: writer}
	buffered.line("// Code generated by ts-go-run-types. DO NOT EDIT.")
	buffered.line("// Source: reflection-shape runtime cache for mion runtypes.")
	buffered.line("")

	// 1. Declare every type as a top-level `export const` containing only scalar fields.
	for _, runType := range dump.RunTypes {
		if runType == nil {
			continue
		}
		buffered.line(fmt.Sprintf("export const %s = %s;", varName(settings, runType.ID), headerLiteral(runType)))
	}

	buffered.line("")
	buffered.line("// --- knot refs, parents, and runtime values ---")
	for _, runType := range dump.RunTypes {
		if runType == nil {
			continue
		}
		writeFooter(buffered, settings, runType)
	}

	return buffered.err
}

// varName turns a hash id into a JS const identifier by prepending the
// module's configured prefix. Hashes (and the `x_*` synthetic ids) are
// already valid JS identifiers, so no per-character sanitisation is needed.
func varName(settings constants.CacheModuleSettings, id string) string {
	return settings.VarPrefix + id
}

// headerLiteral renders only the scalar fields of runType. Reference-bearing
// slots and runtime-special literals are emitted in the footer. The wire id
// is always emitted: runtime consumers (parent-chain traversal, dedup
// lookups by id) need it on every node, so the renderer can't strip it.
func headerLiteral(runType *protocol.RunType) string {
	fields := map[string]any{"id": runType.ID, "kind": int(runType.Kind)}
	if runType.TypeName != "" {
		fields["typeName"] = runType.TypeName
	}
	if runType.Name != "" {
		fields["name"] = runType.Name
	}
	if runType.Literal != nil && !isFooterLiteral(runType) {
		fields["literal"] = runType.Literal
	}
	if runType.Optional {
		fields["optional"] = true
	}
	if runType.Readonly {
		fields["readonly"] = true
	}
	if runType.Abstract {
		fields["abstract"] = true
	}
	if runType.Static {
		fields["static"] = true
	}
	if runType.Visibility != nil {
		fields["visibility"] = *runType.Visibility
	}
	if runType.IsSafePropName {
		fields["isSafePropName"] = true
	}
	if runType.IsUnionDiscriminator {
		fields["isUnionDiscriminator"] = true
	}
	if runType.Position != nil {
		fields["position"] = *runType.Position
	}
	if runType.Inlined {
		fields["inlined"] = true
	}
	if len(runType.Flags) > 0 {
		fields["flags"] = runType.Flags
	}
	if runType.Description != "" {
		fields["description"] = runType.Description
	}
	if runType.Default != nil {
		fields["default"] = runType.Default
	}
	if len(runType.Enum) > 0 {
		fields["enum"] = runType.Enum
	}
	if len(runType.Values) > 0 {
		fields["values"] = runType.Values
	}
	return mustJSON(fields)
}

// isFooterLiteral reports whether runType.Literal needs special construction
// in the footer (bigint / symbol / regexp) rather than inline JSON.
func isFooterLiteral(runType *protocol.RunType) bool {
	if runType.Literal == nil {
		return false
	}
	for _, flag := range runType.Flags {
		if flag == "bigint" || flag == "symbol" {
			return true
		}
	}
	if literalMap, ok := runType.Literal.(map[string]any); ok {
		if _, hasRegexp := literalMap["regexp"]; hasRegexp {
			return true
		}
	}
	return false
}

// writeFooter fills runType's reference-bearing fields and runtime-special values.
func writeFooter(buffered *bufWriter, settings constants.CacheModuleSettings, runType *protocol.RunType) {
	name := varName(settings, runType.ID)
	if runType.Child != nil {
		buffered.line(fmt.Sprintf("%s.child = %s;", name, derefExpr(settings, runType.Child)))
	}
	if runType.Index != nil {
		buffered.line(fmt.Sprintf("%s.index = %s;", name, derefExpr(settings, runType.Index)))
	}
	if runType.Return != nil {
		buffered.line(fmt.Sprintf("%s.return = %s;", name, derefExpr(settings, runType.Return)))
	}
	if runType.IndexT != nil {
		buffered.line(fmt.Sprintf("%s.indexType = %s;", name, derefExpr(settings, runType.IndexT)))
	}
	if len(runType.Parameters) > 0 {
		buffered.line(fmt.Sprintf("%s.parameters = [%s];", name, joinRefs(settings, runType.Parameters)))
		for _, parameter := range runType.Parameters {
			if parameter.Kind == protocol.KindRef {
				buffered.line(fmt.Sprintf("%s.parent = %s;", varName(settings, parameter.ID), name))
			}
		}
	}
	if len(runType.Children) > 0 {
		buffered.line(fmt.Sprintf("%s.children = [%s];", name, joinRefs(settings, runType.Children)))
		for _, child := range runType.Children {
			if child.Kind == protocol.KindRef {
				buffered.line(fmt.Sprintf("%s.parent = %s;", varName(settings, child.ID), name))
			}
		}
	}
	// safeUnionChildren — same ref objects as Children, reordered so
	// superset shapes precede their subset equivalents. Emitted as a
	// parallel array; consumers derive per-member safe position via
	// `safeUnionChildren.indexOf(member)`. The JSON wire form carries
	// per-ref `safeUnionPosition`; that field is intentionally NOT
	// reproduced in the in-memory module shape because canonical nodes
	// are shared singletons and can't hold a per-parent position.
	if len(runType.SafeUnionChildren) > 0 {
		buffered.line(fmt.Sprintf("%s.safeUnionChildren = [%s];", name, joinRefs(settings, runType.SafeUnionChildren)))
	}
	// decorators — surviving object-literal types from a collapsed
	// `primitive & {brand}` intersection.
	if len(runType.Decorators) > 0 {
		buffered.line(fmt.Sprintf("%s.decorators = [%s];", name, joinRefs(settings, runType.Decorators)))
	}
	if len(runType.TypeArguments) > 0 {
		buffered.line(fmt.Sprintf("%s.typeArguments = [%s];", name, joinRefs(settings, runType.TypeArguments)))
	}
	if len(runType.Arguments) > 0 {
		buffered.line(fmt.Sprintf("%s.arguments = [%s];", name, joinRefs(settings, runType.Arguments)))
	}
	if len(runType.ExtendsArguments) > 0 {
		buffered.line(fmt.Sprintf("%s.extendsArguments = [%s];", name, joinRefs(settings, runType.ExtendsArguments)))
	}
	if len(runType.Implements) > 0 {
		buffered.line(fmt.Sprintf("%s.implements = [%s];", name, joinRefs(settings, runType.Implements)))
	}

	// classType — built-in constructors looked up on globalThis so the
	// generated module needs zero runtime imports.
	if runType.ClassRef != nil && runType.ClassRef.Builtin != "" {
		buffered.line(fmt.Sprintf("%s.classType = globalThis.%s;", name, runType.ClassRef.Builtin))
	}

	// Footer-only literals.
	if isFooterLiteral(runType) {
		buffered.line(fmt.Sprintf("%s.literal = %s;", name, footerLiteralExpr(runType)))
	}
}

// footerLiteralExpr renders a runtime-special literal as a JS expression.
func footerLiteralExpr(runType *protocol.RunType) string {
	for _, flag := range runType.Flags {
		if flag == "bigint" {
			literalString, _ := runType.Literal.(string)
			return fmt.Sprintf("BigInt(%q)", literalString)
		}
		if flag == "symbol" {
			if literalMap, ok := runType.Literal.(map[string]any); ok {
				if name, ok := literalMap["symbol"].(string); ok {
					return fmt.Sprintf("Symbol(%q)", name)
				}
			}
			return "Symbol()"
		}
	}
	if literalMap, ok := runType.Literal.(map[string]any); ok {
		if regexpRaw, ok := literalMap["regexp"].(map[string]any); ok {
			source, _ := regexpRaw["source"].(string)
			flags, _ := regexpRaw["flags"].(string)
			return fmt.Sprintf("/%s/%s", source, flags)
		}
	}
	return mustJSON(runType.Literal)
}

// derefExpr renders a single child slot. Refs become bare const names;
// inline Types become JSON literals.
func derefExpr(settings constants.CacheModuleSettings, runType *protocol.RunType) string {
	if runType == nil {
		return "undefined"
	}
	if runType.Kind == protocol.KindRef {
		return varName(settings, runType.ID)
	}
	return mustJSON(runType)
}

func joinRefs(settings constants.CacheModuleSettings, runTypes []*protocol.RunType) string {
	parts := make([]string, len(runTypes))
	for i, runType := range runTypes {
		parts[i] = derefExpr(settings, runType)
	}
	return strings.Join(parts, ", ")
}

func mustJSON(value any) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return fmt.Sprintf("/* json err: %v */ undefined", err)
	}
	return string(encoded)
}

type bufWriter struct {
	writer io.Writer
	err    error
}

func (buffered *bufWriter) line(line string) {
	if buffered.err != nil {
		return
	}
	_, buffered.err = io.WriteString(buffered.writer, line+"\n")
}
