package emit

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/mionkit/ts-run-types/internal/protocol"
)

// TSModule writes the runtime artifact: a self-contained TS module declaring
// every cached type as a top-level `const t<N>`, then a footer block that
// resolves refs and wires up `parent` by direct assignment so consumers
// receive a fully-knotted deepkit `Type` graph from `__runtypes.get(id)`.
//
// Layout:
//
//	import type { Type, ReflectionKind } from "@deepkit/type";
//	const t0: any = { kind: 5 };               // string
//	const t1: any = { kind: 16, name: "f" };   // function (refs nilled below)
//	// --- footer: knot refs and parents ---
//	t1.parameters = [t2];   t2.parent = t1;
//	t1.return = t0;
//	export const __runtypes = new Map<number, Type>([[0,t0],[1,t1],[2,t2]]);
//	export const __sites = [...];
//
// The header literal carries every primitive scalar (kind, name, optional,
// readonly, literal value) so consumers can already see the shape of each
// type at the declaration site. The footer fills the slots that hold *Type
// references — those are the only places we need cycles for.
func TSModule(w io.Writer, d protocol.Dump) error {
	bw := &bufWriter{w: w}
	bw.line("// Code generated by ts-run-types. DO NOT EDIT.")
	bw.line("// Source: deepkit/type-shaped runtime cache for mion runtypes.")
	bw.line("")
	bw.line(`import type { Type } from "@deepkit/type";`)
	bw.line("")

	// 1. Declare every type as a header literal containing only scalar fields.
	// Reference-bearing slots (type, return, parameters, types, index, …) are
	// left undefined here and filled in by the footer.
	for _, t := range d.Types {
		if t == nil {
			continue
		}
		bw.line(fmt.Sprintf("const t%d: any = %s;", t.ID, headerLiteral(t)))
	}

	bw.line("")
	bw.line("// --- knot refs and parents ---")

	// 2. Footer: fill child slots and parent links by direct assignment.
	for _, t := range d.Types {
		if t == nil {
			continue
		}
		writeFooter(bw, t)
	}

	// 3. Exports.
	bw.line("")
	bw.line("export const __runtypes = new Map<number, Type>([")
	for _, t := range d.Types {
		if t == nil {
			continue
		}
		bw.line(fmt.Sprintf("  [%d, t%d],", t.ID, t.ID))
	}
	bw.line("]);")
	bw.line("")
	bw.line(fmt.Sprintf("export const __sites: { file: string; pos: number; id: number }[] = %s;", mustJSON(d.Sites)))

	return bw.err
}

// headerLiteral renders only the scalar fields of t. Reference-bearing slots
// are emitted in the footer to break cycles.
func headerLiteral(t *protocol.Type) string {
	m := map[string]any{
		"kind": int(t.Kind),
	}
	if t.TypeName != "" {
		m["typeName"] = t.TypeName
	}
	if t.Name != "" {
		m["name"] = t.Name
	}
	if t.Literal != nil {
		m["literal"] = t.Literal
	}
	if t.Optional {
		m["optional"] = true
	}
	if t.Readonly {
		m["readonly"] = true
	}
	if t.Abstract {
		m["abstract"] = true
	}
	if t.Static {
		m["static"] = true
	}
	if t.Inlined {
		m["inlined"] = true
	}
	if len(t.Flags) > 0 {
		m["flags"] = t.Flags
	}
	if t.Description != "" {
		m["description"] = t.Description
	}
	if t.Default != nil {
		m["default"] = t.Default
	}
	return mustJSON(m)
}

// writeFooter fills in t's reference-bearing fields.
func writeFooter(bw *bufWriter, t *protocol.Type) {
	if t.Type != nil {
		bw.line(fmt.Sprintf("t%d.type = %s;", t.ID, derefExpr(t.Type)))
		if needsParent(t.Kind) {
			// Inline parent links for child Types we own — only relevant when
			// `t.type` is itself a child member node we created (e.g.
			// TypeArray.type points at a Type but doesn't own its parent).
		}
	}
	if t.Index != nil {
		bw.line(fmt.Sprintf("t%d.index = %s;", t.ID, derefExpr(t.Index)))
	}
	if t.Return != nil {
		bw.line(fmt.Sprintf("t%d.return = %s;", t.ID, derefExpr(t.Return)))
	}
	if t.IndexT != nil && t.IndexT.ID >= 0 {
		bw.line(fmt.Sprintf("t%d.indexType = %s;", t.ID, derefExpr(t.IndexT)))
	}
	if len(t.Parameters) > 0 {
		bw.line(fmt.Sprintf("t%d.parameters = [%s];", t.ID, joinRefs(t.Parameters)))
		// Set parent on each parameter — these are owned children of t.
		for _, p := range t.Parameters {
			if p.Kind == protocol.KindRef {
				bw.line(fmt.Sprintf("t%d.parent = t%d;", p.ID, t.ID))
			}
		}
	}
	if len(t.Types) > 0 {
		bw.line(fmt.Sprintf("t%d.types = [%s];", t.ID, joinRefs(t.Types)))
		for _, m := range t.Types {
			if m.Kind == protocol.KindRef {
				bw.line(fmt.Sprintf("t%d.parent = t%d;", m.ID, t.ID))
			}
		}
	}
	if len(t.TypeArguments) > 0 {
		bw.line(fmt.Sprintf("t%d.typeArguments = [%s];", t.ID, joinRefs(t.TypeArguments)))
	}
	if len(t.Arguments) > 0 {
		bw.line(fmt.Sprintf("t%d.arguments = [%s];", t.ID, joinRefs(t.Arguments)))
	}
	if len(t.ExtendsArguments) > 0 {
		bw.line(fmt.Sprintf("t%d.extendsArguments = [%s];", t.ID, joinRefs(t.ExtendsArguments)))
	}
	if len(t.Implements) > 0 {
		bw.line(fmt.Sprintf("t%d.implements = [%s];", t.ID, joinRefs(t.Implements)))
	}
	if t.ClassRef != nil {
		bw.line(fmt.Sprintf("t%d.classRef = %s;", t.ID, mustJSON(t.ClassRef)))
	}
}

// derefExpr renders a single child slot. If the slot is a ref sentinel we
// emit the bare const name (`t5`); otherwise we fall back to a JSON literal.
func derefExpr(t *protocol.Type) string {
	if t == nil {
		return "undefined"
	}
	if t.Kind == protocol.KindRef {
		return fmt.Sprintf("t%d", t.ID)
	}
	return mustJSON(t)
}

// joinRefs renders a list of child slots as a JS array of t<N> references.
func joinRefs(ts []*protocol.Type) string {
	parts := make([]string, len(ts))
	for i, t := range ts {
		parts[i] = derefExpr(t)
	}
	return strings.Join(parts, ", ")
}

// needsParent reports whether this kind owns inline children that should have
// `parent` set to the containing node.
func needsParent(k protocol.ReflectionKind) bool {
	switch k {
	case protocol.KindObjectLiteral, protocol.KindClass, protocol.KindFunction,
		protocol.KindMethod, protocol.KindMethodSignature, protocol.KindCallSignature,
		protocol.KindTuple, protocol.KindUnion, protocol.KindIntersection,
		protocol.KindEnum:
		return true
	}
	return false
}

func mustJSON(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("/* json err: %v */ undefined", err)
	}
	return string(b)
}

// bufWriter wraps an io.Writer with a line helper and sticky-error tracking.
type bufWriter struct {
	w   io.Writer
	err error
}

func (b *bufWriter) line(s string) {
	if b.err != nil {
		return
	}
	_, b.err = io.WriteString(b.w, s+"\n")
}

// stableSitesByFile sorts a slice of sites for deterministic output. Used by
// tests that compare against goldens.
func stableSitesByFile(in []protocol.Site) []protocol.Site {
	out := append([]protocol.Site(nil), in...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].File != out[j].File {
			return out[i].File < out[j].File
		}
		if out[i].Pos != out[j].Pos {
			return out[i].Pos < out[j].Pos
		}
		return out[i].ID < out[j].ID
	})
	return out
}

// Stable returns a copy of d with sites sorted deterministically. Types are
// already in id-order from the cache.
func Stable(d protocol.Dump) protocol.Dump {
	return protocol.Dump{Types: d.Types, Sites: stableSitesByFile(d.Sites)}
}
