package emit

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/mionkit/ts-run-types/internal/protocol"
)

// TSModule writes the runtime artifact: a self-contained TS module declaring
// every cached type as a top-level `const t_<hash>`, then a footer block that
// resolves refs and wires up `parent` by direct assignment so consumers
// receive a fully-knotted reflection `Type` graph from `__runtypes.get(hash)`.
//
// Footer special-cases:
//   - Literal bigint  → `t.literal = BigInt("…")`
//   - Literal symbol  → `t.literal = Symbol("…")`
//   - Literal regexp  → `t.literal = new RegExp(source, flags)`
//   - Class with ClassRef.Builtin → `t.classType = globalThis.<Name>`
func TSModule(w io.Writer, d protocol.Dump) error {
	bw := &bufWriter{w: w}
	bw.line("// Code generated by ts-run-types. DO NOT EDIT.")
	bw.line("// Source: reflection-shape runtime cache for mion runtypes.")
	bw.line("")
	bw.line("// Local Type alias keeps this module self-contained (no external imports).")
	bw.line("type Type = any;")
	bw.line("")

	// 1. Declare every type as a header literal containing only scalar fields.
	for _, t := range d.Types {
		if t == nil {
			continue
		}
		bw.line(fmt.Sprintf("const %s: any = %s;", varName(t.ID), headerLiteral(t)))
	}

	bw.line("")
	bw.line("// --- knot refs, parents, and runtime values ---")
	for _, t := range d.Types {
		if t == nil {
			continue
		}
		writeFooter(bw, t)
	}

	bw.line("")
	bw.line("export const __runtypes = new Map<string, Type>([")
	for _, t := range d.Types {
		if t == nil {
			continue
		}
		bw.line(fmt.Sprintf("  [%q, %s],", t.ID, varName(t.ID)))
	}
	bw.line("]);")
	bw.line("")
	bw.line(fmt.Sprintf("export const __sites: { file: string; pos: number; id: string }[] = %s;", mustJSON(d.Sites)))

	return bw.err
}

// varName turns a hash id into a JS const identifier. Hashes start with a
// letter (per QuickHash); we still prefix with `t_` for readability and to
// keep the synthetic ids ("x_…") syntactically valid.
func varName(id string) string {
	return "t_" + sanitiseID(id)
}

// sanitiseID replaces any non-identifier-safe characters with `_`.
func sanitiseID(id string) string {
	b := make([]byte, 0, len(id))
	for i := 0; i < len(id); i++ {
		c := id[i]
		switch {
		case c >= 'a' && c <= 'z',
			c >= 'A' && c <= 'Z',
			c >= '0' && c <= '9',
			c == '_':
			b = append(b, c)
		default:
			b = append(b, '_')
		}
	}
	return string(b)
}

// headerLiteral renders only the scalar fields of t. Reference-bearing slots
// and runtime-special literals are emitted in the footer.
func headerLiteral(t *protocol.Type) string {
	m := map[string]any{"kind": int(t.Kind)}
	if t.TypeName != "" {
		m["typeName"] = t.TypeName
	}
	if t.Name != "" {
		m["name"] = t.Name
	}
	if t.Literal != nil && !isFooterLiteral(t) {
		m["literal"] = t.Literal
	}
	if t.Optional {
		m["optional"] = true
	}
	if t.Readonly {
		m["readonly"] = true
	}
	if t.Abstract {
		m["abstract"] = true
	}
	if t.Static {
		m["static"] = true
	}
	if t.Inlined {
		m["inlined"] = true
	}
	if len(t.Flags) > 0 {
		m["flags"] = t.Flags
	}
	if t.Description != "" {
		m["description"] = t.Description
	}
	if t.Default != nil {
		m["default"] = t.Default
	}
	if len(t.Enum) > 0 {
		m["enum"] = t.Enum
	}
	if len(t.Values) > 0 {
		m["values"] = t.Values
	}
	return mustJSON(m)
}

// isFooterLiteral reports whether t.Literal needs special construction in
// the footer (bigint / symbol / regexp) rather than inline JSON.
func isFooterLiteral(t *protocol.Type) bool {
	if t.Literal == nil {
		return false
	}
	for _, f := range t.Flags {
		if f == "bigint" || f == "symbol" {
			return true
		}
	}
	if m, ok := t.Literal.(map[string]any); ok {
		if _, hasRegexp := m["regexp"]; hasRegexp {
			return true
		}
	}
	return false
}

// writeFooter fills t's reference-bearing fields and runtime-special values.
func writeFooter(bw *bufWriter, t *protocol.Type) {
	v := varName(t.ID)
	if t.Type != nil {
		bw.line(fmt.Sprintf("%s.type = %s;", v, derefExpr(t.Type)))
	}
	if t.Index != nil {
		bw.line(fmt.Sprintf("%s.index = %s;", v, derefExpr(t.Index)))
	}
	if t.Return != nil {
		bw.line(fmt.Sprintf("%s.return = %s;", v, derefExpr(t.Return)))
	}
	if t.IndexT != nil {
		bw.line(fmt.Sprintf("%s.indexType = %s;", v, derefExpr(t.IndexT)))
	}
	if len(t.Parameters) > 0 {
		bw.line(fmt.Sprintf("%s.parameters = [%s];", v, joinRefs(t.Parameters)))
		for _, p := range t.Parameters {
			if p.Kind == protocol.KindRef {
				bw.line(fmt.Sprintf("%s.parent = %s;", varName(p.ID), v))
			}
		}
	}
	if len(t.Types) > 0 {
		bw.line(fmt.Sprintf("%s.types = [%s];", v, joinRefs(t.Types)))
		for _, m := range t.Types {
			if m.Kind == protocol.KindRef {
				bw.line(fmt.Sprintf("%s.parent = %s;", varName(m.ID), v))
			}
		}
	}
	if len(t.TypeArguments) > 0 {
		bw.line(fmt.Sprintf("%s.typeArguments = [%s];", v, joinRefs(t.TypeArguments)))
	}
	if len(t.Arguments) > 0 {
		bw.line(fmt.Sprintf("%s.arguments = [%s];", v, joinRefs(t.Arguments)))
	}
	if len(t.ExtendsArguments) > 0 {
		bw.line(fmt.Sprintf("%s.extendsArguments = [%s];", v, joinRefs(t.ExtendsArguments)))
	}
	if len(t.Implements) > 0 {
		bw.line(fmt.Sprintf("%s.implements = [%s];", v, joinRefs(t.Implements)))
	}

	// classType — built-in constructors looked up on globalThis so the
	// generated module needs zero runtime imports.
	if t.ClassRef != nil && t.ClassRef.Builtin != "" {
		bw.line(fmt.Sprintf("%s.classType = (globalThis as any).%s;", v, t.ClassRef.Builtin))
	}

	// Footer-only literals.
	if isFooterLiteral(t) {
		bw.line(fmt.Sprintf("%s.literal = %s;", v, footerLiteralExpr(t)))
	}
}

// footerLiteralExpr renders a runtime-special literal as a JS expression.
func footerLiteralExpr(t *protocol.Type) string {
	for _, f := range t.Flags {
		if f == "bigint" {
			s, _ := t.Literal.(string)
			return fmt.Sprintf("BigInt(%q)", s)
		}
		if f == "symbol" {
			if m, ok := t.Literal.(map[string]any); ok {
				if name, ok := m["symbol"].(string); ok {
					return fmt.Sprintf("Symbol(%q)", name)
				}
			}
			return "Symbol()"
		}
	}
	if m, ok := t.Literal.(map[string]any); ok {
		if rxRaw, ok := m["regexp"].(map[string]any); ok {
			source, _ := rxRaw["source"].(string)
			flags, _ := rxRaw["flags"].(string)
			return fmt.Sprintf("new RegExp(%q, %q)", source, flags)
		}
	}
	return mustJSON(t.Literal)
}

// derefExpr renders a single child slot. Refs become bare const names;
// inline Types become JSON literals.
func derefExpr(t *protocol.Type) string {
	if t == nil {
		return "undefined"
	}
	if t.Kind == protocol.KindRef {
		return varName(t.ID)
	}
	return mustJSON(t)
}

func joinRefs(ts []*protocol.Type) string {
	parts := make([]string, len(ts))
	for i, t := range ts {
		parts[i] = derefExpr(t)
	}
	return strings.Join(parts, ", ")
}

func mustJSON(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("/* json err: %v */ undefined", err)
	}
	return string(b)
}

type bufWriter struct {
	w   io.Writer
	err error
}

func (b *bufWriter) line(s string) {
	if b.err != nil {
		return
	}
	_, b.err = io.WriteString(b.w, s+"\n")
}

// stableSitesByFile sorts sites for deterministic output.
func stableSitesByFile(in []protocol.Site) []protocol.Site {
	out := append([]protocol.Site(nil), in...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].File != out[j].File {
			return out[i].File < out[j].File
		}
		if out[i].Pos != out[j].Pos {
			return out[i].Pos < out[j].Pos
		}
		return out[i].ID < out[j].ID
	})
	return out
}

// Stable returns a copy of d with sites sorted deterministically. Types are
// already in id-order from the cache.
func Stable(d protocol.Dump) protocol.Dump {
	return protocol.Dump{Types: d.Types, Sites: stableSitesByFile(d.Sites)}
}
