package emit

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/mionkit/ts-run-types/internal/protocol"
)

// TSModule writes the runtime artifact: a self-contained JS module declaring
// every cached type as a top-level `const t_<hash>`, then a footer block that
// resolves refs and wires up `parent` by direct assignment so consumers
// receive a fully-knotted reflection `RunType` graph from `__runtypes.get(hash)`.
// Output is plain JS (no TS annotations) so Vite/oxc / node-vm can consume
// it without a TS loader. Callers that want a .ts file just rename it.
//
// Footer special-cases:
//   - Literal bigint  → `t.literal = BigInt("…")`
//   - Literal symbol  → `t.literal = Symbol("…")`
//   - Literal regexp  → `t.literal = new RegExp(source, flags)`
//   - Class with ClassRef.Builtin → `t.classType = globalThis.<Name>`
func TSModule(writer io.Writer, dump protocol.Dump) error {
	buffered := &bufWriter{writer: writer}
	buffered.line("// Code generated by ts-go-run-types. DO NOT EDIT.")
	buffered.line("// Source: reflection-shape runtime cache for mion runtypes.")
	buffered.line("")

	// 1. Declare every type as a header literal containing only scalar fields.
	for _, runType := range dump.RunTypes {
		if runType == nil {
			continue
		}
		buffered.line(fmt.Sprintf("const %s = %s;", varName(runType.ID), headerLiteral(runType)))
	}

	buffered.line("")
	buffered.line("// --- knot refs, parents, and runtime values ---")
	for _, runType := range dump.RunTypes {
		if runType == nil {
			continue
		}
		writeFooter(buffered, runType)
	}

	buffered.line("")
	buffered.line("export const __runtypes = new Map([")
	for _, runType := range dump.RunTypes {
		if runType == nil {
			continue
		}
		buffered.line(fmt.Sprintf("  [%q, %s],", runType.ID, varName(runType.ID)))
	}
	buffered.line("]);")
	buffered.line("")
	buffered.line(fmt.Sprintf("export const __sites = %s;", mustJSON(dump.Sites)))

	return buffered.err
}

// varName turns a hash id into a JS const identifier. Hashes start with a
// letter (per QuickHash); we still prefix with `t_` for readability and to
// keep the synthetic ids ("x_…") syntactically valid.
func varName(id string) string {
	return "t_" + sanitiseID(id)
}

// sanitiseID replaces any non-identifier-safe characters with `_`.
func sanitiseID(id string) string {
	buf := make([]byte, 0, len(id))
	for i := 0; i < len(id); i++ {
		char := id[i]
		switch {
		case char >= 'a' && char <= 'z',
			char >= 'A' && char <= 'Z',
			char >= '0' && char <= '9',
			char == '_':
			buf = append(buf, char)
		default:
			buf = append(buf, '_')
		}
	}
	return string(buf)
}

// headerLiteral renders only the scalar fields of runType. Reference-bearing
// slots and runtime-special literals are emitted in the footer. The wire id
// is always emitted: runtime consumers (parent-chain traversal, dedup
// lookups by id) need it on every node, so the renderer can't strip it.
func headerLiteral(runType *protocol.RunType) string {
	fields := map[string]any{"id": runType.ID, "kind": int(runType.Kind)}
	if runType.TypeName != "" {
		fields["typeName"] = runType.TypeName
	}
	if runType.Name != "" {
		fields["name"] = runType.Name
	}
	if runType.Literal != nil && !isFooterLiteral(runType) {
		fields["literal"] = runType.Literal
	}
	if runType.Optional {
		fields["optional"] = true
	}
	if runType.Readonly {
		fields["readonly"] = true
	}
	if runType.Abstract {
		fields["abstract"] = true
	}
	if runType.Static {
		fields["static"] = true
	}
	if runType.Inlined {
		fields["inlined"] = true
	}
	if len(runType.Flags) > 0 {
		fields["flags"] = runType.Flags
	}
	if runType.Description != "" {
		fields["description"] = runType.Description
	}
	if runType.Default != nil {
		fields["default"] = runType.Default
	}
	if len(runType.Enum) > 0 {
		fields["enum"] = runType.Enum
	}
	if len(runType.Values) > 0 {
		fields["values"] = runType.Values
	}
	return mustJSON(fields)
}

// isFooterLiteral reports whether runType.Literal needs special construction
// in the footer (bigint / symbol / regexp) rather than inline JSON.
func isFooterLiteral(runType *protocol.RunType) bool {
	if runType.Literal == nil {
		return false
	}
	for _, flag := range runType.Flags {
		if flag == "bigint" || flag == "symbol" {
			return true
		}
	}
	if literalMap, ok := runType.Literal.(map[string]any); ok {
		if _, hasRegexp := literalMap["regexp"]; hasRegexp {
			return true
		}
	}
	return false
}

// writeFooter fills runType's reference-bearing fields and runtime-special values.
func writeFooter(buffered *bufWriter, runType *protocol.RunType) {
	name := varName(runType.ID)
	if runType.Child != nil {
		buffered.line(fmt.Sprintf("%s.child = %s;", name, derefExpr(runType.Child)))
	}
	if runType.Index != nil {
		buffered.line(fmt.Sprintf("%s.index = %s;", name, derefExpr(runType.Index)))
	}
	if runType.Return != nil {
		buffered.line(fmt.Sprintf("%s.return = %s;", name, derefExpr(runType.Return)))
	}
	if runType.IndexT != nil {
		buffered.line(fmt.Sprintf("%s.indexType = %s;", name, derefExpr(runType.IndexT)))
	}
	if len(runType.Parameters) > 0 {
		buffered.line(fmt.Sprintf("%s.parameters = [%s];", name, joinRefs(runType.Parameters)))
		for _, parameter := range runType.Parameters {
			if parameter.Kind == protocol.KindRef {
				buffered.line(fmt.Sprintf("%s.parent = %s;", varName(parameter.ID), name))
			}
		}
	}
	if len(runType.Children) > 0 {
		buffered.line(fmt.Sprintf("%s.children = [%s];", name, joinRefs(runType.Children)))
		for _, child := range runType.Children {
			if child.Kind == protocol.KindRef {
				buffered.line(fmt.Sprintf("%s.parent = %s;", varName(child.ID), name))
			}
		}
	}
	if len(runType.TypeArguments) > 0 {
		buffered.line(fmt.Sprintf("%s.typeArguments = [%s];", name, joinRefs(runType.TypeArguments)))
	}
	if len(runType.Arguments) > 0 {
		buffered.line(fmt.Sprintf("%s.arguments = [%s];", name, joinRefs(runType.Arguments)))
	}
	if len(runType.ExtendsArguments) > 0 {
		buffered.line(fmt.Sprintf("%s.extendsArguments = [%s];", name, joinRefs(runType.ExtendsArguments)))
	}
	if len(runType.Implements) > 0 {
		buffered.line(fmt.Sprintf("%s.implements = [%s];", name, joinRefs(runType.Implements)))
	}

	// classType — built-in constructors looked up on globalThis so the
	// generated module needs zero runtime imports.
	if runType.ClassRef != nil && runType.ClassRef.Builtin != "" {
		buffered.line(fmt.Sprintf("%s.classType = globalThis.%s;", name, runType.ClassRef.Builtin))
	}

	// Footer-only literals.
	if isFooterLiteral(runType) {
		buffered.line(fmt.Sprintf("%s.literal = %s;", name, footerLiteralExpr(runType)))
	}
}

// footerLiteralExpr renders a runtime-special literal as a JS expression.
func footerLiteralExpr(runType *protocol.RunType) string {
	for _, flag := range runType.Flags {
		if flag == "bigint" {
			literalString, _ := runType.Literal.(string)
			return fmt.Sprintf("BigInt(%q)", literalString)
		}
		if flag == "symbol" {
			if literalMap, ok := runType.Literal.(map[string]any); ok {
				if name, ok := literalMap["symbol"].(string); ok {
					return fmt.Sprintf("Symbol(%q)", name)
				}
			}
			return "Symbol()"
		}
	}
	if literalMap, ok := runType.Literal.(map[string]any); ok {
		if regexpRaw, ok := literalMap["regexp"].(map[string]any); ok {
			source, _ := regexpRaw["source"].(string)
			flags, _ := regexpRaw["flags"].(string)
			return fmt.Sprintf("new RegExp(%q, %q)", source, flags)
		}
	}
	return mustJSON(runType.Literal)
}

// derefExpr renders a single child slot. Refs become bare const names;
// inline Types become JSON literals.
func derefExpr(runType *protocol.RunType) string {
	if runType == nil {
		return "undefined"
	}
	if runType.Kind == protocol.KindRef {
		return varName(runType.ID)
	}
	return mustJSON(runType)
}

func joinRefs(runTypes []*protocol.RunType) string {
	parts := make([]string, len(runTypes))
	for i, runType := range runTypes {
		parts[i] = derefExpr(runType)
	}
	return strings.Join(parts, ", ")
}

func mustJSON(value any) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return fmt.Sprintf("/* json err: %v */ undefined", err)
	}
	return string(encoded)
}

type bufWriter struct {
	writer io.Writer
	err    error
}

func (buffered *bufWriter) line(line string) {
	if buffered.err != nil {
		return
	}
	_, buffered.err = io.WriteString(buffered.writer, line+"\n")
}

// stableSitesByFile sorts sites for deterministic output.
func stableSitesByFile(sites []protocol.Site) []protocol.Site {
	out := append([]protocol.Site(nil), sites...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].File != out[j].File {
			return out[i].File < out[j].File
		}
		if out[i].Pos != out[j].Pos {
			return out[i].Pos < out[j].Pos
		}
		return out[i].ID < out[j].ID
	})
	return out
}

// Stable returns a copy of dump with sites sorted deterministically. Types are
// already in id-order from the cache.
func Stable(dump protocol.Dump) protocol.Dump {
	return protocol.Dump{RunTypes: dump.RunTypes, Sites: stableSitesByFile(dump.Sites)}
}
