// Renders the virtual runtypes-cache module from an in-memory Dump. Mirrors
// internal/emit/tsmodule.go so plugin-emitted modules are identical to what
// the Go binary writes via `--out-ts`.

import { KIND_REF, type Site, type Type } from "./protocol.js";

export interface RenderInput {
  types: Type[];
  sites: Site[];
  // language="ts" (default) emits the deepkit-typed module; "js" omits all
  // type annotations so the output is directly evaluable by node/vm without
  // a TS loader. Used by tests.
  language?: "ts" | "js";
}

export function renderCacheModule(input: RenderInput): string {
  const ts = (input.language ?? "ts") === "ts";
  const lines: string[] = [];
  lines.push("// Generated by vite-plugin-runtypes. Do not edit.");
  lines.push("// Source: deepkit/type-shaped runtime cache for mion runtypes.");
  lines.push("");
  if (ts) {
    lines.push(`import type { Type } from "@deepkit/type";`);
    lines.push("");
  }

  const annot = ts ? ": any " : " ";
  for (const t of input.types) {
    if (!t) continue;
    lines.push(`const t${t.id ?? 0}${annot}= ${JSON.stringify(headerLiteral(t))};`);
  }

  lines.push("");
  lines.push("// --- knot refs and parents ---");

  for (const t of input.types) {
    if (!t) continue;
    appendFooter(lines, t);
  }

  lines.push("");
  const mapAnnot = ts ? "<number, Type>" : "";
  lines.push(`export const __runtypes = new Map${mapAnnot}([`);
  for (const t of input.types) {
    if (!t) continue;
    lines.push(`  [${t.id ?? 0}, t${t.id ?? 0}],`);
  }
  lines.push("]);");
  lines.push("");
  const sitesAnnot = ts ? ": { file: string; pos: number; id: number }[]" : "";
  lines.push(`export const __sites${sitesAnnot} = ${JSON.stringify(input.sites)};`);
  return lines.join("\n") + "\n";
}

function headerLiteral(t: Type): Record<string, unknown> {
  const m: Record<string, unknown> = { kind: t.kind };
  if (t.typeName) m.typeName = t.typeName;
  if (t.name) m.name = t.name;
  if (t.literal !== undefined) m.literal = t.literal;
  if (t.optional) m.optional = true;
  if (t.readonly) m.readonly = true;
  if (t.abstract) m.abstract = true;
  if (t.static) m.static = true;
  if (t.inlined) m.inlined = true;
  if (t.flags && t.flags.length) m.flags = t.flags;
  if (t.description) m.description = t.description;
  if (t.default !== undefined) m.default = t.default;
  return m;
}

function appendFooter(lines: string[], t: Type): void {
  if (t.type) {
    lines.push(`t${t.id}.type = ${derefExpr(t.type)};`);
  }
  if (t.index) {
    lines.push(`t${t.id}.index = ${derefExpr(t.index)};`);
  }
  if (t.return) {
    lines.push(`t${t.id}.return = ${derefExpr(t.return)};`);
  }
  if (t.indexType && t.indexType.id !== undefined && t.indexType.id >= 0) {
    lines.push(`t${t.id}.indexType = ${derefExpr(t.indexType)};`);
  }
  if (t.parameters && t.parameters.length) {
    lines.push(`t${t.id}.parameters = [${t.parameters.map(derefExpr).join(", ")}];`);
    for (const p of t.parameters) {
      if (p.kind === KIND_REF) lines.push(`t${p.id}.parent = t${t.id};`);
    }
  }
  if (t.types && t.types.length) {
    lines.push(`t${t.id}.types = [${t.types.map(derefExpr).join(", ")}];`);
    for (const m of t.types) {
      if (m.kind === KIND_REF) lines.push(`t${m.id}.parent = t${t.id};`);
    }
  }
  if (t.typeArguments && t.typeArguments.length) {
    lines.push(`t${t.id}.typeArguments = [${t.typeArguments.map(derefExpr).join(", ")}];`);
  }
  if (t.arguments && t.arguments.length) {
    lines.push(`t${t.id}.arguments = [${t.arguments.map(derefExpr).join(", ")}];`);
  }
  if (t.extendsArguments && t.extendsArguments.length) {
    lines.push(
      `t${t.id}.extendsArguments = [${t.extendsArguments.map(derefExpr).join(", ")}];`,
    );
  }
  if (t.implements && t.implements.length) {
    lines.push(`t${t.id}.implements = [${t.implements.map(derefExpr).join(", ")}];`);
  }
  if (t.classRef) {
    lines.push(`t${t.id}.classRef = ${JSON.stringify(t.classRef)};`);
  }
}

function derefExpr(t: Type | undefined): string {
  if (!t) return "undefined";
  if (t.kind === KIND_REF) return `t${t.id}`;
  return JSON.stringify(t);
}
