// Code generated by cmd/gen-ts-constants. DO NOT EDIT.
// Source: internal/constants/constants.go.
// Regenerate via `pnpm run gen:ts-constants` after changing the Go source.

export interface CacheModuleSettings {
  readonly name: string;
  readonly varPrefix: string;
}

export const CACHE_MODULES = {
  runTypes: {name: 'runTypesModule', varPrefix: 't_'},
} as const satisfies Record<string, CacheModuleSettings>;

export const RUNTYPES_VAR_PREFIX = 't_';
export const RUNTYPES_MODULE_NAME = 'runTypesModule';
