// Code generated by cmd/gen-ts-constants. DO NOT EDIT.
// Source: internal/constants/constants.go.
// Regenerate via `pnpm run gen:ts-constants` after changing the Go source.

export interface CacheModuleSettings {
  readonly name: string;
  readonly varPrefix: string;
  readonly tag: string;
}

export const CACHE_MODULES = {
  hasUnknownKeys: {name: 'hasUnknownKeysModule', varPrefix: 'g_huk_', tag: 'huk'},
  isType: {name: 'isTypeModule', varPrefix: 'g_it_', tag: 'it'},
  prepareForJson: {name: 'prepareForJsonModule', varPrefix: 'g_pj_', tag: 'pj'},
  prepareForJsonFlat: {name: 'prepareForJsonFlatModule', varPrefix: 'g_pjf_', tag: 'pjf'},
  pureFns: {name: 'pureFnsModule', varPrefix: '', tag: ''},
  restoreFromJson: {name: 'restoreFromJsonModule', varPrefix: 'g_rj_', tag: 'rj'},
  restoreFromJsonFlat: {name: 'restoreFromJsonFlatModule', varPrefix: 'g_rjf_', tag: 'rjf'},
  runTypes: {name: 'runTypesModule', varPrefix: 't_', tag: 't'},
  stringifyJson: {name: 'stringifyJsonModule', varPrefix: 'g_sj_', tag: 'sj'},
  stringifyJsonFlat: {name: 'stringifyJsonFlatModule', varPrefix: 'g_sjf_', tag: 'sjf'},
  stripUnknownKeys: {name: 'stripUnknownKeysModule', varPrefix: 'g_suk_', tag: 'suk'},
  typeErrors: {name: 'typeErrorsModule', varPrefix: 'g_te_', tag: 'te'},
  unknownKeyErrors: {name: 'unknownKeyErrorsModule', varPrefix: 'g_uke_', tag: 'uke'},
  unknownKeysToUndefined: {name: 'unknownKeysToUndefinedModule', varPrefix: 'g_uku_', tag: 'uku'},
} as const satisfies Record<string, CacheModuleSettings>;

export const HASUNKNOWNKEYS_VAR_PREFIX = 'g_huk_';
export const HASUNKNOWNKEYS_MODULE_NAME = 'hasUnknownKeysModule';
export const HASUNKNOWNKEYS_TAG = 'huk';
export const ISTYPE_VAR_PREFIX = 'g_it_';
export const ISTYPE_MODULE_NAME = 'isTypeModule';
export const ISTYPE_TAG = 'it';
export const PREPAREFORJSON_VAR_PREFIX = 'g_pj_';
export const PREPAREFORJSON_MODULE_NAME = 'prepareForJsonModule';
export const PREPAREFORJSON_TAG = 'pj';
export const PREPAREFORJSONFLAT_VAR_PREFIX = 'g_pjf_';
export const PREPAREFORJSONFLAT_MODULE_NAME = 'prepareForJsonFlatModule';
export const PREPAREFORJSONFLAT_TAG = 'pjf';
export const PUREFNS_VAR_PREFIX = '';
export const PUREFNS_MODULE_NAME = 'pureFnsModule';
export const PUREFNS_TAG = '';
export const RESTOREFROMJSON_VAR_PREFIX = 'g_rj_';
export const RESTOREFROMJSON_MODULE_NAME = 'restoreFromJsonModule';
export const RESTOREFROMJSON_TAG = 'rj';
export const RESTOREFROMJSONFLAT_VAR_PREFIX = 'g_rjf_';
export const RESTOREFROMJSONFLAT_MODULE_NAME = 'restoreFromJsonFlatModule';
export const RESTOREFROMJSONFLAT_TAG = 'rjf';
export const RUNTYPES_VAR_PREFIX = 't_';
export const RUNTYPES_MODULE_NAME = 'runTypesModule';
export const RUNTYPES_TAG = 't';
export const STRINGIFYJSON_VAR_PREFIX = 'g_sj_';
export const STRINGIFYJSON_MODULE_NAME = 'stringifyJsonModule';
export const STRINGIFYJSON_TAG = 'sj';
export const STRINGIFYJSONFLAT_VAR_PREFIX = 'g_sjf_';
export const STRINGIFYJSONFLAT_MODULE_NAME = 'stringifyJsonFlatModule';
export const STRINGIFYJSONFLAT_TAG = 'sjf';
export const STRIPUNKNOWNKEYS_VAR_PREFIX = 'g_suk_';
export const STRIPUNKNOWNKEYS_MODULE_NAME = 'stripUnknownKeysModule';
export const STRIPUNKNOWNKEYS_TAG = 'suk';
export const TYPEERRORS_VAR_PREFIX = 'g_te_';
export const TYPEERRORS_MODULE_NAME = 'typeErrorsModule';
export const TYPEERRORS_TAG = 'te';
export const UNKNOWNKEYERRORS_VAR_PREFIX = 'g_uke_';
export const UNKNOWNKEYERRORS_MODULE_NAME = 'unknownKeyErrorsModule';
export const UNKNOWNKEYERRORS_TAG = 'uke';
export const UNKNOWNKEYSTOUNDEFINED_VAR_PREFIX = 'g_uku_';
export const UNKNOWNKEYSTOUNDEFINED_MODULE_NAME = 'unknownKeysToUndefinedModule';
export const UNKNOWNKEYSTOUNDEFINED_TAG = 'uku';

export const REFLECTION_SUB_KIND = {
  mapKey: 1801,
  mapValue: 1802,
  setItem: 1803,
  date: 2001,
  map: 2002,
  set: 2003,
  nonSerializable: 2004,
} as const;
export type ReflectionSubKind = (typeof REFLECTION_SUB_KIND)[keyof typeof REFLECTION_SUB_KIND];

export const NON_SERIALIZABLE_GLOBALS = [
  'Error',
  'EvalError',
  'RangeError',
  'ReferenceError',
  'SyntaxError',
  'TypeError',
  'URIError',
  'AggregateError',
  'WeakMap',
  'WeakSet',
  'DataView',
  'ArrayBuffer',
  'SharedArrayBuffer',
  'Float32Array',
  'Float64Array',
  'Int8Array',
  'Int16Array',
  'Int32Array',
  'Uint8Array',
  'Uint8ClampedArray',
  'Uint16Array',
  'Uint32Array',
  'BigInt64Array',
  'BigUint64Array',
  'Generator',
  'GeneratorFunction',
  'AsyncGenerator',
  'Iterator',
  'AsyncGeneratorFunction',
  'AsyncIterator',
] as const;
