// Code generated by ts-run-types. DO NOT EDIT.
// Source: reflection-shape runtime cache for mion runtypes.

// Local Type alias keeps this module self-contained (no external imports).
type Type = any;

const t0: any = {"kind":30};
const t1: any = {"kind":5};
const t2: any = {"kind":18,"name":"name"};
const t3: any = {"kind":33,"name":"sayHello"};
const t4: any = {"kind":6};
const t5: any = {"kind":18,"name":"a"};
const t6: any = {"kind":18,"name":"b"};
const t7: any = {"kind":33,"name":"sum"};

// --- knot refs and parents ---
t0.types = [t3, t7];
t3.parent = t0;
t7.parent = t0;
t2.type = t1;
t3.return = t1;
t3.parameters = [t2];
t2.parent = t3;
t5.type = t4;
t6.type = t4;
t7.return = t4;
t7.parameters = [t5, t6];
t5.parent = t7;
t6.parent = t7;

export const __runtypes = new Map<number, Type>([
  [0, t0],
  [1, t1],
  [2, t2],
  [3, t3],
  [4, t4],
  [5, t5],
  [6, t6],
  [7, t7],
]);

export const __sites: { file: string; pos: number; id: number }[] = [{"file":"03-inference-router/input.ts","pos":231,"id":0}];
