package mirror

// Property / fuzz test for the enrich-mirror reconciler (Reconcile).
//
// It models the HMR edit loop the reconciler actually runs in: starting from a
// known-good mirror generated by the real emitter (Scaffold), it applies a
// random sequence of HIGH-FIDELITY, human-like edits to the SOURCE type (rename
// a field, add/delete a field, change a field's type, rename the whole type),
// re-deriving the desired const set the compiler would produce and re-running
// Reconcile after every edit — exactly the half-typed terrain HMR feeds it.
//
// After every step it asserts the reconciler's invariants:
//   - the mirror still parses (no syntax error introduced),
//   - a second reconcile is a byte-identical no-op (one-step idempotence /
//     convergence), and
//   - every authored leaf value survives — live, carried across a rename, or
//     preserved verbatim inside an @rtOrphan/@rtOrphanChild carcass. Authored
//     content is NEVER silently lost; that is the bug class with the worst blast
//     radius (a user's friendly-error template / mock pool gone for good).
//
// Failures are reproducible by seed and SHRUNK to the shortest failing edit
// sequence, so a red run names the minimal repro directly.

import (
	"fmt"
	"hash/fnv"
	"math/rand"
	"sort"
	"strings"
	"testing"

	"github.com/mionkit/ts-runtypes/internal/enrich"
)

const (
	fuzzMirrorPath = "/rt/gen/model.ts"
	fuzzSourcePath = "/src/model.ts"
)

// fieldKind is a primitive source field type. Kept deliberately small: the
// reconciler's bug surface lives in the merge/orphan/rename machinery, not in
// type breadth, so tiny inputs find it fastest.
type fieldKind int

const (
	kindString fieldKind = iota
	kindNumber
	kindBoolean
)

func (kind fieldKind) tsName() string {
	switch kind {
	case kindNumber:
		return "number"
	case kindBoolean:
		return "boolean"
	default:
		return "string"
	}
}

// childID is the field's structural child id — derived from its TYPE ALONE (not
// its key), mirroring the real RunType.ID: a string field is the same id whether
// it is called `name` or `fullName`. That key-independence is what lets the
// reconciler's Tier-2 rename pairing carry an authored value across a key rename;
// changing the kind changes the id and forces a type-change replace.
func (kind fieldKind) childID() string {
	return "c" + kind.tsName()
}

type modelField struct {
	key  string
	kind fieldKind
}

// model is the source-side state: one named type with primitive fields. The
// desired const set (Spec) the compiler would emit is a pure function of it.
type model struct {
	typeName string
	fields   []modelField
}

// structuralID is the type's @rtType id. It folds in the type NAME plus the
// SHAPE (field keys + kinds): per the reconciler's design a whole-type rename
// CHANGES the id (the old const orphans, a new one is appended), and any field
// add / remove / rename / retype changes it too (so the marker drifts and the
// reconcile falls back to the var-name match, then field-level rename detection).
func structuralID(input model) string {
	pairs := make([]string, len(input.fields))
	for i, field := range input.fields {
		pairs[i] = field.key + ":" + field.kind.tsName()
	}
	sort.Strings(pairs)
	digest := fnv.New32a()
	digest.Write([]byte(input.typeName + "|" + strings.Join(pairs, ",")))
	return fmt.Sprintf("t%08x", digest.Sum32())
}

// friendlyBody / mockBody render the EMPTY desired skeletons the emitter
// produces (the authored values live only in the existing mirror, never in the
// freshly-derived desired set). Their format matches the real skeleton emitter
// so a pristine Scaffold is already a reconcile fixpoint.
func friendlyBody(input model) string {
	parts := []string{"$label: ''"}
	for _, field := range input.fields {
		parts = append(parts, field.key+": {$label: ''}")
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func mockBody(input model) string {
	parts := make([]string, 0, len(input.fields))
	for _, field := range input.fields {
		parts = append(parts, field.key+": {pool: []}")
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

// deriveSpec builds the desired reconcile Spec the compiler would hand the
// reconciler for the current model — single source file, single named type,
// both friendly + mock forms.
func deriveSpec(input model) Spec {
	childIDs := map[string]string{}
	for _, field := range input.fields {
		childIDs[field.key] = field.kind.childID()
	}
	named := enrich.NamedConst{
		TypeName:    input.typeName,
		DeclFile:    fuzzSourcePath,
		FriendlyVar: "friendly" + input.typeName,
		MockVar:     "mock" + input.typeName,
		Friendly:    friendlyBody(input),
		Mock:        mockBody(input),
		TypeID:      structuralID(input),
		ChildIDs:    childIDs,
	}
	return Spec{
		MirrorPath:   fuzzMirrorPath,
		SourceFile:   fuzzSourcePath,
		Out:          fuzzMirrorPath, // single-file: no cross-file import wiring
		WantFriendly: true,
		WantMock:     true,
		Consts:       []enrich.NamedConst{named},
	}
}

// renderSource is the synthetic `.ts` the orphan judgement reads (via the
// injected readSource) to decide whether a const's annotated type is still
// declared. It declares exactly the current type.
func renderSource(input model) string {
	var builder strings.Builder
	builder.WriteString("export interface " + input.typeName + " {\n")
	for _, field := range input.fields {
		builder.WriteString("  " + field.key + ": " + field.kind.tsName() + ";\n")
	}
	builder.WriteString("}\n")
	return builder.String()
}

// injectAuthored simulates the user filling in real data: it replaces every
// empty skeleton placeholder ($label: ” and pool: []) with a UNIQUE sentinel
// value and returns the sentinels. Sentinels contain no `*/` or backslash, so
// they survive a carcass round-trip verbatim and the value-preservation oracle
// is a plain substring check.
// Sentinels are FIXED-WIDTH within a distinct prefix (AUTHL / AUTHP / KEEPC /
// the numeric reserved form) so none is a substring of another — otherwise a
// plain Contains check for "AUTHL1" would spuriously pass on a surviving
// "AUTHL12", masking a real loss.
func injectAuthored(text string) (string, []string) {
	var sentinels []string
	counter := 0
	for strings.Contains(text, "$label: ''") {
		counter++
		sentinel := fmt.Sprintf("AUTHL%04d", counter)
		text = strings.Replace(text, "$label: ''", "$label: '"+sentinel+"'", 1)
		sentinels = append(sentinels, sentinel)
	}
	for strings.Contains(text, "pool: []") {
		counter++
		sentinel := fmt.Sprintf("AUTHP%04d", counter)
		text = strings.Replace(text, "pool: []", "pool: ['"+sentinel+"']", 1)
		sentinels = append(sentinels, sentinel)
	}
	return text, sentinels
}

// initialMirror generates the known-good starting mirror from the real emitter,
// then authors every placeholder so there is data to (try to) lose.
func initialMirror(input model) (string, []string, error) {
	content, _, err := Scaffold(deriveSpec(input), "")
	if err != nil {
		return "", nil, err
	}
	if content == "" {
		return "", nil, fmt.Errorf("Scaffold produced no content for %d fields", len(input.fields))
	}
	authored, sentinels := injectAuthored(content)
	return authored, sentinels, nil
}

// caseState threads one fuzz case: its seeded RNG, the evolving source model and
// mirror text, the authored sentinels that must never be lost, a fresh-id
// counter (unique field/type names), and the human-readable edit log used for
// the shrunk repro.
type caseState struct {
	rng      *rand.Rand
	current  model
	mirror   string
	authored []string
	log      []string
	nextID   int
}

func (state *caseState) freshKey() string {
	state.nextID++
	return fmt.Sprintf("field%d", state.nextID)
}

// --- mutators: each mirrors one thing a human does in an editor. They return
// false when not applicable (e.g. delete with no fields), so the driver retries.

func (state *caseState) renameField() bool {
	if len(state.current.fields) == 0 {
		return false
	}
	index := state.rng.Intn(len(state.current.fields))
	old := state.current.fields[index].key
	renamed := state.freshKey()
	state.current.fields[index].key = renamed
	state.log = append(state.log, fmt.Sprintf("renameField %s -> %s", old, renamed))
	return true
}

func (state *caseState) addField() bool {
	key := state.freshKey()
	kind := fieldKind(state.rng.Intn(3))
	state.current.fields = append(state.current.fields, modelField{key: key, kind: kind})
	state.log = append(state.log, fmt.Sprintf("addField %s:%s", key, kind.tsName()))
	return true
}

func (state *caseState) deleteField() bool {
	if len(state.current.fields) == 0 {
		return false
	}
	index := state.rng.Intn(len(state.current.fields))
	dropped := state.current.fields[index].key
	state.current.fields = append(state.current.fields[:index], state.current.fields[index+1:]...)
	state.log = append(state.log, fmt.Sprintf("deleteField %s", dropped))
	return true
}

func (state *caseState) changeFieldType() bool {
	if len(state.current.fields) == 0 {
		return false
	}
	index := state.rng.Intn(len(state.current.fields))
	old := state.current.fields[index].kind
	next := old
	for next == old {
		next = fieldKind(state.rng.Intn(3))
	}
	state.current.fields[index].kind = next
	state.log = append(state.log, fmt.Sprintf("changeFieldType %s %s -> %s",
		state.current.fields[index].key, old.tsName(), next.tsName()))
	return true
}

func (state *caseState) renameType() bool {
	old := state.current.typeName
	state.nextID++
	renamed := fmt.Sprintf("Type%d", state.nextID)
	state.current.typeName = renamed
	state.log = append(state.log, fmt.Sprintf("renameType %s -> %s", old, renamed))
	return true
}

// liveBody locates a LIVE (non-carcass) const's object-literal opening brace in
// the current mirror, with its friendly/mock form — the anchor the mirror-side
// mutators edit. Using the parsed index guarantees we never write into an
// @rtOrphan carcass (which would corrupt a comment).
type liveBody struct {
	openBrace  int
	isFriendly bool
}

func liveBodies(mirror string) []liveBody {
	index, err := ParseMirror(fuzzMirrorPath, []byte(mirror))
	if err != nil {
		return nil
	}
	var out []liveBody
	for _, entry := range index.consts {
		if entry.body == nil {
			continue
		}
		open := entry.body.Pos()
		for open < len(mirror) && mirror[open] != '{' {
			open++
		}
		if open < len(mirror) {
			out = append(out, liveBody{openBrace: open, isFriendly: entry.isFriendly})
		}
	}
	return out
}

// addCommentToMirror simulates the user dropping an inline note into a node —
// the spec flags comments as easy to lose in a property-level splice. The
// reconcile must carry it through (live, or folded into a carcass).
func (state *caseState) addCommentToMirror() bool {
	bodies := liveBodies(state.mirror)
	if len(bodies) == 0 {
		return false
	}
	target := bodies[state.rng.Intn(len(bodies))]
	state.nextID++
	sentinel := fmt.Sprintf("KEEPC%04d", state.nextID)
	at := target.openBrace + 1
	state.mirror = state.mirror[:at] + " /* " + sentinel + " */" + state.mirror[at:]
	state.authored = append(state.authored, sentinel)
	state.log = append(state.log, "addCommentToMirror "+sentinel)
	return true
}

// addReservedPropToMirror simulates the user authoring an extra reserved-key
// constraint the scaffold did not include (e.g. a `min` on a mock node). Reserved
// keys are node meta, never data fields, so the reconcile must preserve them.
func (state *caseState) addReservedPropToMirror() bool {
	var mocks []liveBody
	for _, body := range liveBodies(state.mirror) {
		if !body.isFriendly {
			mocks = append(mocks, body)
		}
	}
	if len(mocks) == 0 {
		return false
	}
	target := mocks[state.rng.Intn(len(mocks))]
	state.nextID++
	sentinel := fmt.Sprintf("1%05d", state.nextID) // fixed-width numeric, collision-free
	at := target.openBrace + 1
	state.mirror = state.mirror[:at] + " min: " + sentinel + "," + state.mirror[at:]
	state.authored = append(state.authored, sentinel)
	state.log = append(state.log, "addReservedPropToMirror min:"+sentinel)
	return true
}

// checkOracles asserts the three invariants on the current mirror; it returns ""
// on success or a description of the first violation.
func (state *caseState) checkOracles(readSource func(string) (string, error), where string) string {
	// 1. Parseable — no syntax error was introduced.
	if _, err := ParseMirror(fuzzMirrorPath, []byte(state.mirror)); err != nil {
		return fmt.Sprintf("[%s] result no longer parses: %v", where, err)
	}
	// 2. One-step idempotence / convergence — reconciling the result is a
	//    byte-identical no-op.
	spec := deriveSpec(state.current)
	out, changed, err := Reconcile(spec, []byte(state.mirror), readSource)
	if err != nil {
		return fmt.Sprintf("[%s] second reconcile errored: %v", where, err)
	}
	if changed || string(out) != state.mirror {
		return fmt.Sprintf("[%s] NOT idempotent (changed=%v)\n--- first result ---\n%s\n--- second result ---\n%s",
			where, changed, state.mirror, string(out))
	}
	// 3. Value preservation — no authored value was lost.
	for _, sentinel := range state.authored {
		if !strings.Contains(state.mirror, sentinel) {
			return fmt.Sprintf("[%s] authored value %q was LOST:\n%s", where, sentinel, state.mirror)
		}
	}
	return ""
}

func (state *caseState) failureReport(detail string) string {
	return fmt.Sprintf("%s\n--- edit sequence (%d) ---\n%s\n--- final mirror ---\n%s",
		detail, len(state.log), strings.Join(state.log, "\n"), state.mirror)
}

// runPropertyCase plays one seeded case of up to `steps` edits, returning
// (failed, report). It is PURE in (seed, steps): the same arguments replay the
// same edits, so the driver can shrink by re-running with fewer steps.
func runPropertyCase(seed int64, steps int) (bool, string) {
	state := &caseState{rng: rand.New(rand.NewSource(seed))}
	state.current = model{
		typeName: "Model",
		fields: []modelField{
			{key: "alpha", kind: kindString},
			{key: "beta", kind: kindNumber},
		},
	}
	mirror, sentinels, err := initialMirror(state.current)
	if err != nil {
		return true, fmt.Sprintf("initial scaffold failed: %v", err)
	}
	state.mirror = mirror
	state.authored = sentinels
	readSource := func(string) (string, error) { return renderSource(state.current), nil }

	if report := state.checkOracles(readSource, "initial"); report != "" {
		return true, state.failureReport(report)
	}

	mutators := []func() bool{
		state.renameField,
		state.addField,
		state.deleteField,
		state.changeFieldType,
		state.renameType,
		state.addCommentToMirror,
		state.addReservedPropToMirror,
	}
	for step := 0; step < steps; step++ {
		applied := false
		for tries := 0; tries < 8 && !applied; tries++ {
			applied = mutators[state.rng.Intn(len(mutators))]()
		}
		if !applied {
			continue
		}
		spec := deriveSpec(state.current)
		out, _, err := Reconcile(spec, []byte(state.mirror), readSource)
		if err != nil {
			return true, state.failureReport(fmt.Sprintf("step %d: Reconcile errored: %v", step, err))
		}
		state.mirror = string(out)
		if report := state.checkOracles(readSource, fmt.Sprintf("step %d: %s", step, state.log[len(state.log)-1])); report != "" {
			return true, state.failureReport(report)
		}
	}
	return false, ""
}

// TestReconcile_Property is the fuzz driver: it runs many seeded cases and, on
// the first failure, shrinks to the shortest failing prefix and reports it.
func TestReconcile_Property(t *testing.T) {
	cases, steps := 120, 20
	if testing.Short() {
		cases, steps = 40, 10
	}
	for caseIndex := 0; caseIndex < cases; caseIndex++ {
		seed := int64(caseIndex) + 1
		failed, _ := runPropertyCase(seed, steps)
		if !failed {
			continue
		}
		// Shrink: the smallest step count that still fails.
		minSteps := steps
		for k := 0; k <= steps; k++ {
			if shorter, _ := runPropertyCase(seed, k); shorter {
				minSteps = k
				break
			}
		}
		_, report := runPropertyCase(seed, minSteps)
		t.Fatalf("property failed (seed=%d, minimal steps=%d):\n%s", seed, minSteps, report)
	}
}
