// Code generated by cmd/gen-fn-hashes. DO NOT EDIT.
// Source: internal/cachegen/operations (the registry + fnhash.go salt).
// Regenerate via `pnpm run gen:fn-hashes` after changing an operation, a
// validate option, a JSON strategy, or the fnHash salt.
//
// Every fnHash here is VERSION-INDEPENDENT (operations.fnHashSalt no longer
// folds constants.Version), so the same table ships for every ts-runtypes
// release: a consumer resolves `fnKey (+ options) → fnHash` once and never
// re-pins on a version bump. The runtime cache key is `<fnHash>_<typeId>`;
// its typeId half (injected by the plugin) still carries the version.

export type FnHashAxis = 'none' | 'validateOptions' | 'jsonStrategy';

export interface FnHashEntry {
  readonly axis: FnHashAxis;
  /** jsonStrategy only: the strategy token applied when options omit `strategy`. */
  readonly defaultVariant?: string;
  /** Variant token → fnHash. Token is '' for option-less families, the validate
   *  variant suffix ('', 'NL', 'NA', 'NLA'), or the JSON strategy name. */
  readonly variants: Readonly<Record<string, string>>;
}

export const FN_HASHES = {
  cj: {axis: 'none', variants: {'': 'xnN'}},
  cjr: {axis: 'none', variants: {'': 'Siw'}},
  fb: {axis: 'none', variants: {'': 'mY6'}},
  fmt: {axis: 'none', variants: {'': 'SS6'}},
  huk: {axis: 'none', variants: {'': 'trR'}},
  jsonDecoder: {axis: 'jsonStrategy', defaultVariant: 'strip', variants: {compact: 'MCy', preserve: 'J5l', strip: 'fDV'}},
  jsonEncoder: {
    axis: 'jsonStrategy',
    defaultVariant: 'clone',
    variants: {clone: 'wUi', compact: 'yeS', direct: 'y0u', mutate: 'z1L'},
  },
  pj: {axis: 'none', variants: {'': 'tt1'}},
  pjs: {axis: 'none', variants: {'': 'oak'}},
  rj: {axis: 'none', variants: {'': 'X13'}},
  sj: {axis: 'none', variants: {'': 'qm4'}},
  suk: {axis: 'none', variants: {'': 'rRP'}},
  tb: {axis: 'none', variants: {'': 'plZ'}},
  uke: {axis: 'none', variants: {'': 'XFJ'}},
  uku: {axis: 'none', variants: {'': 'emC'}},
  ukuw: {axis: 'none', variants: {'': 'N3x'}},
  val: {axis: 'validateOptions', variants: {'': 'nPZ', NA: 'WeU', NL: 'N7J', NLA: 'GYK'}},
  verr: {axis: 'validateOptions', variants: {'': 'pBb', NA: 'UKg', NL: 'LD5', NLA: 'Yk4'}},
} as const satisfies Record<string, FnHashEntry>;

/** ValidateOptions name → single-letter token, in Go declaration order
 *  (constants.ValidateOptions). The validate variant suffix is 'N' followed by
 *  the letters of the present options concatenated in THIS order. */
export const VALIDATE_OPTION_LETTERS = [
  ['noLiterals', 'L'],
  ['noIsArrayCheck', 'A'],
] as const satisfies ReadonlyArray<readonly [string, string]>;
