package purefn

import (
	"fmt"
	"io"
	"strings"
)

// ParsedFnsModule writes the JS source body for the
// `virtual:runtypes-parsed-fns` module. Each entry renders as a property of
// the exported `parsedFns` map, keyed by "<namespace>::<functionName>".
//
// Output is deterministic: entries are emitted in the order they appear in
// the input slice (ExtractFromProgram already sorts alphabetically by key).
func ParsedFnsModule(writer io.Writer, entries []ParsedFn) error {
	var b strings.Builder
	b.WriteString("// Code generated by ts-go-run-types. DO NOT EDIT.\n")
	b.WriteString("// Source: parsedFn extraction from registerPureFnFactory call sites.\n")
	b.WriteString("'use strict';\n")
	b.WriteString("export const parsedFns = {\n")
	for _, entry := range entries {
		fmt.Fprintf(&b, "  %s: {bodyHash: %s, paramNames: %s, code: %s},\n",
			quoteJS(entry.Key()),
			quoteJS(entry.BodyHash),
			paramNamesJS(entry.ParamNames),
			quoteJS(entry.Code),
		)
	}
	b.WriteString("};\n")
	_, err := io.WriteString(writer, b.String())
	return err
}

// quoteJS renders s as a single-quoted JS string literal. Mirrors the same
// helper in internal/jitfn/quote.go (kept private to this package to avoid
// a cross-package edge for one tiny helper).
func quoteJS(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('\'')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '\'':
			b.WriteString(`\'`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('\'')
	return b.String()
}

func paramNamesJS(names []string) string {
	if len(names) == 0 {
		return "[]"
	}
	parts := make([]string, len(names))
	for i, name := range names {
		parts[i] = quoteJS(name)
	}
	return "[" + strings.Join(parts, ",") + "]"
}
