package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
)

// kindEntry is one resolved constant parsed out of protocol.go or
// subkind.go: the Go identifier, the JS-side name it maps to, and the
// integer value that flows through the wire.
type kindEntry struct {
	GoName string
	JsName string
	Value  int
}

// jsNameOverrides handles cases where the algorithmic lowerCamelCase
// from the Go name doesn't match the desired JS-side name. Currently
// only `bigInt` -> `bigint` so the JS dispatcher matches TypeScript's
// primitive `bigint` literal type.
var jsNameOverrides = map[string]string{
	"bigInt": "bigint",
}

// repoRoot returns the repository root derived from this source file's
// location, so the generator and its test work regardless of the
// caller's working directory.
func repoRoot() string {
	_, thisFile, _, _ := runtime.Caller(0)
	return filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", ".."))
}

// runTypeKindOutputPath is the absolute path of the TS file we emit.
func runTypeKindOutputPath() string {
	return filepath.Join(repoRoot(), "packages", "ts-go-run-types", "src", "runTypeKind.ts")
}

// Generate builds the full body of `runTypeKind.ts` from the live
// protocol const declarations. The output is deterministic and depends
// only on the contents of `internal/protocol/protocol.go` +
// `internal/protocol/subkind.go`.
func Generate() (string, error) {
	kinds, err := parseConsts(
		filepath.Join(repoRoot(), "internal", "protocol", "protocol.go"),
		"ReflectionKind",
		"Kind",
	)
	if err != nil {
		return "", fmt.Errorf("parse protocol.go: %w", err)
	}
	subKinds, err := parseConsts(
		filepath.Join(repoRoot(), "internal", "protocol", "subkind.go"),
		"ReflectionSubKind",
		"SubKind",
	)
	if err != nil {
		return "", fmt.Errorf("parse subkind.go: %w", err)
	}

	var out strings.Builder
	out.WriteString("// ============================================================================\n")
	out.WriteString("//                            AUTO-GENERATED FILE\n")
	out.WriteString("//                            DO NOT EDIT MANUALLY\n")
	out.WriteString("// ============================================================================\n")
	out.WriteString("//\n")
	out.WriteString("// Generated by cmd/gen-run-type-kind from:\n")
	out.WriteString("//   - internal/protocol/protocol.go\n")
	out.WriteString("//   - internal/protocol/subkind.go\n")
	out.WriteString("//\n")
	out.WriteString("// To update: change the Go source, then run:\n")
	out.WriteString("//\n")
	out.WriteString("//     pnpm run gen:run-type-kind\n")
	out.WriteString("//\n")
	out.WriteString("// The TestRunTypeKindFileInSync Go test fails on any drift between this\n")
	out.WriteString("// file and the generator's output, so local edits will be caught by CI.\n")
	out.WriteString("//\n")
	out.WriteString("// Numeric discriminators that JS-side consumers use to dispatch on the\n")
	out.WriteString("// shape of a RunType node in the runTypesCache. Values must match the\n")
	out.WriteString("// Go binary's wire output byte-for-byte.\n")
	out.WriteString("//\n")
	out.WriteString("// ============================================================================\n")
	out.WriteString("\n")

	writeConstObj(&out, "RunTypeKind", kinds)
	out.WriteString("\n")
	out.WriteString("export type RunTypeKindName = keyof typeof RunTypeKind;\n")
	out.WriteString("export type RunTypeKindValue = (typeof RunTypeKind)[RunTypeKindName];\n")
	out.WriteString("\n")

	writeConstObj(&out, "RunTypeSubKind", subKinds)
	out.WriteString("\n")
	out.WriteString("export type RunTypeSubKindName = keyof typeof RunTypeSubKind;\n")
	out.WriteString("export type RunTypeSubKindValue = (typeof RunTypeSubKind)[RunTypeSubKindName];\n")

	return out.String(), nil
}

func writeConstObj(out *strings.Builder, name string, entries []kindEntry) {
	fmt.Fprintf(out, "export const %s = {\n", name)
	for _, entry := range entries {
		fmt.Fprintf(out, "  %s: %d,\n", entry.JsName, entry.Value)
	}
	out.WriteString("} as const;\n")
}

// parseConsts walks the AST of `filename` and returns every top-level
// constant whose declared type is `typeName`, in declaration order,
// with values resolved. Handles two shapes that cover both protocol
// files:
//
//   - iota blocks: `const ( X TypeName = iota; Y; Z; )` — successive
//     identifiers inherit the iota expression with the counter auto-
//     incremented per spec position.
//   - explicit-literal specs: `const X TypeName = 42` and per-spec
//     literals inside a paren block. Negative literals are evaluated
//     via the UnaryExpr branch in `evalIntExpr`.
//
// `prefix` ("Kind" / "SubKind") is stripped from each Go identifier
// before lowerCamelCase conversion to produce the JS-side property name.
func parseConsts(filename, typeName, prefix string) ([]kindEntry, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, nil, 0)
	if err != nil {
		return nil, err
	}

	var result []kindEntry
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}

		var blockType string
		var usesIota bool
		var lastValue int

		for specIndex, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			// Type sticks across specs in a const block — first typed
			// spec sets it; subsequent untyped specs inherit.
			if valueSpec.Type != nil {
				if ident, isIdent := valueSpec.Type.(*ast.Ident); isIdent {
					blockType = ident.Name
				}
			}

			// First spec decides whether this block is iota-counted.
			// Iota auto-increments per spec position within the block.
			if specIndex == 0 && len(valueSpec.Values) > 0 {
				if ident, isIdent := valueSpec.Values[0].(*ast.Ident); isIdent && ident.Name == "iota" {
					usesIota = true
				}
			}

			var value int
			switch {
			case usesIota:
				value = specIndex
			case len(valueSpec.Values) > 0:
				value = evalIntExpr(valueSpec.Values[0])
				lastValue = value
			default:
				value = lastValue
			}

			if blockType != typeName {
				continue
			}

			for _, name := range valueSpec.Names {
				result = append(result, kindEntry{
					GoName: name.Name,
					JsName: goNameToJsName(name.Name, prefix),
					Value:  value,
				})
			}
		}
	}
	return result, nil
}

// evalIntExpr handles the subset of constant expressions our protocol
// consts actually use: integer literals and unary minus. Anything else
// returns 0 (and a regeneration failure would surface as a TestRunType
// KindFileInSync diff).
func evalIntExpr(expr ast.Expr) int {
	switch typed := expr.(type) {
	case *ast.BasicLit:
		if typed.Kind == token.INT {
			parsed, err := strconv.Atoi(typed.Value)
			if err == nil {
				return parsed
			}
		}
	case *ast.UnaryExpr:
		if typed.Op == token.SUB {
			return -evalIntExpr(typed.X)
		}
		return evalIntExpr(typed.X)
	}
	return 0
}

// goNameToJsName strips `prefix` from `goName`, lowercases the first
// letter, and applies any entry from `jsNameOverrides`. So `KindBigInt`
// -> `bigInt` -> `bigint` (override); `KindTemplateLiteral` ->
// `templateLiteral` (algorithmic).
func goNameToJsName(goName, prefix string) string {
	name := strings.TrimPrefix(goName, prefix)
	if name == "" {
		return name
	}
	result := strings.ToLower(name[:1]) + name[1:]
	if override, ok := jsNameOverrides[result]; ok {
		return override
	}
	return result
}
