// gen-run-type-kind regenerates the TS mirror of ReflectionKind and
// ReflectionSubKind from internal/protocol/protocol.go and
// internal/protocol/subkind.go.
//
// The numeric discriminator values MUST match the Go binary's wire
// output byte-for-byte — JS-side consumers dispatch on these values
// to read runTypesCache nodes, so any drift silently breaks the JS
// half. Keep this generator's entry lists in sync with the Go consts
// whenever protocol.go or subkind.go changes.
//
// Run:
//
//	go run ./cmd/gen-run-type-kind > packages/ts-go-run-types/src/runTypeKind.ts
//
// Or via the pnpm script:
//
//	pnpm run gen:run-type-kind
package main

import (
	"fmt"
	"strings"

	"github.com/mionkit/ts-run-types/internal/protocol"
)

type kindEntry struct {
	Name  string
	Value int
}

var kinds = []kindEntry{
	{"never", int(protocol.KindNever)},
	{"any", int(protocol.KindAny)},
	{"unknown", int(protocol.KindUnknown)},
	{"void", int(protocol.KindVoid)},
	{"object", int(protocol.KindObject)},
	{"string", int(protocol.KindString)},
	{"number", int(protocol.KindNumber)},
	{"boolean", int(protocol.KindBoolean)},
	{"symbol", int(protocol.KindSymbol)},
	{"bigint", int(protocol.KindBigInt)},
	{"null", int(protocol.KindNull)},
	{"undefined", int(protocol.KindUndefined)},
	{"regexp", int(protocol.KindRegexp)},
	{"literal", int(protocol.KindLiteral)},
	{"templateLiteral", int(protocol.KindTemplateLiteral)},
	{"property", int(protocol.KindProperty)},
	{"method", int(protocol.KindMethod)},
	{"function", int(protocol.KindFunction)},
	{"parameter", int(protocol.KindParameter)},
	{"promise", int(protocol.KindPromise)},
	{"class", int(protocol.KindClass)},
	{"typeParameter", int(protocol.KindTypeParameter)},
	{"enum", int(protocol.KindEnum)},
	{"union", int(protocol.KindUnion)},
	{"intersection", int(protocol.KindIntersection)},
	{"array", int(protocol.KindArray)},
	{"tuple", int(protocol.KindTuple)},
	{"tupleMember", int(protocol.KindTupleMember)},
	{"enumMember", int(protocol.KindEnumMember)},
	{"rest", int(protocol.KindRest)},
	{"objectLiteral", int(protocol.KindObjectLiteral)},
	{"indexSignature", int(protocol.KindIndexSignature)},
	{"propertySignature", int(protocol.KindPropertySignature)},
	{"methodSignature", int(protocol.KindMethodSignature)},
	{"infer", int(protocol.KindInfer)},
	{"callSignature", int(protocol.KindCallSignature)},
	{"ref", int(protocol.KindRef)},
}

var subKinds = []kindEntry{
	{"none", int(protocol.SubKindNone)},
	{"mapKey", int(protocol.SubKindMapKey)},
	{"mapValue", int(protocol.SubKindMapValue)},
	{"setItem", int(protocol.SubKindSetItem)},
	{"date", int(protocol.SubKindDate)},
	{"map", int(protocol.SubKindMap)},
	{"set", int(protocol.SubKindSet)},
	{"nonSerializable", int(protocol.SubKindNonSerializable)},
}

func main() {
	out := &strings.Builder{}
	out.WriteString("// Code generated by cmd/gen-run-type-kind. DO NOT EDIT.\n")
	out.WriteString("// Source: internal/protocol/protocol.go + internal/protocol/subkind.go\n")
	out.WriteString("// Regenerate via `pnpm run gen:run-type-kind` after changing the Go source.\n")
	out.WriteString("//\n")
	out.WriteString("// Numeric discriminators that JS-side consumers use to dispatch on the\n")
	out.WriteString("// shape of a RunType node in the runTypesCache. Values must match the\n")
	out.WriteString("// Go binary's wire output byte-for-byte.\n")
	out.WriteString("\n")

	out.WriteString("export const RunTypeKind = {\n")
	for _, entry := range kinds {
		out.WriteString(fmt.Sprintf("  %s: %d,\n", entry.Name, entry.Value))
	}
	out.WriteString("} as const;\n")
	out.WriteString("\n")

	out.WriteString("export type RunTypeKindName = keyof typeof RunTypeKind;\n")
	out.WriteString("export type RunTypeKindValue = (typeof RunTypeKind)[RunTypeKindName];\n")
	out.WriteString("\n")

	out.WriteString("export const RunTypeSubKind = {\n")
	for _, entry := range subKinds {
		out.WriteString(fmt.Sprintf("  %s: %d,\n", entry.Name, entry.Value))
	}
	out.WriteString("} as const;\n")
	out.WriteString("\n")

	out.WriteString("export type RunTypeSubKindName = keyof typeof RunTypeSubKind;\n")
	out.WriteString("export type RunTypeSubKindValue = (typeof RunTypeSubKind)[RunTypeSubKindName];\n")

	fmt.Print(out.String())
}
