package jitfn

import (
	"fmt"
	"io"

	"github.com/mionkit/ts-run-types/internal/constants"
	"github.com/mionkit/ts-run-types/internal/protocol"
)

// IsTypeModule writes the runtime artifact for the `virtual:runtypes-isType`
// module: one `export function get_isType_<hash>(utl) { … }` factory per
// RunType this package's dispatch knows how to emit. The module does NOT
// pre-invoke any factory; consumers import the factory and call it
// themselves with whatever `utl` they want bound into the closure.
//
// Mirrors the structure of internal/emit/runtypes_module.go: one
// top-level export per cached RunType, no footer (the isType factory
// has no refs to knot — the closure body is the only payload).
//
// Kinds the dispatch doesn't yet handle are silently skipped. The
// alternative (panicking) would crash the whole module for the
// presence of one unsupported kind, which makes the rollout
// kind-by-kind impossible. The runtime acceptance test asserts on the
// expected `KindString` hash — if dispatch_istype.go regresses for
// KindString the test fails loudly there.
func IsTypeModule(writer io.Writer, dump protocol.Dump) error {
	settings := constants.CacheModules["isType"]
	buffered := &lineWriter{writer: writer}
	buffered.line("// Code generated by ts-go-run-types. DO NOT EDIT.")
	buffered.line("// Source: precompiled isType validators for mion runtypes.")
	buffered.line("")

	for _, runType := range dump.RunTypes {
		if runType == nil || !isImplemented(runType.Kind) {
			continue
		}
		factory := renderIsTypeFactory(settings, runType)
		if factory == "" {
			continue
		}
		buffered.line("export " + factory)
	}

	return buffered.err
}

// isTypeInnerPrefix is the prefix for the INNER validator function
// inside each factory — what mion calls `jitFnHash` (the name used for
// self-recursive calls inside the body). The outer factory's name comes
// from CacheModules["isType"].VarPrefix (currently "get_isType_"). Keep
// the relationship `VarPrefix == "get_" + isTypeInnerPrefix` so the
// emitted JS matches mion's printClosure pattern (`get_<fnName>` wraps
// `<fnName>`). The two prefixes intentionally don't live on the same
// constant: VarPrefix is consumer-facing (in the CacheModuleSettings
// mirror), while the inner prefix is an internal codegen detail.
const isTypeInnerPrefix = "isType_"

// renderIsTypeFactory builds the inner function declaration via the
// Compiler, then wraps it in the outer `get_isType_<hash>(utl)`
// factory. Returns an empty string if the compilation result is a noop
// (no point shipping a function that just returns true unconditionally
// — same call site can default to a noop on the consumer side).
func renderIsTypeFactory(settings constants.CacheModuleSettings, runType *protocol.RunType) string {
	factoryName := settings.VarPrefix + runType.ID
	innerName := isTypeInnerPrefix + runType.ID
	compiler := NewIsTypeCompiler(runType, innerName)
	compiler.Compile(runType, CodeE, JitFnIsType)
	innerFn := compiler.CreateJitFunction()
	if compiler.IsNoop() {
		// `function name(v){return true}` carries no useful runtime
		// information; consumers can default to `() => true` without
		// the wire cost. Mirrors mion's `isNoop` short-circuit
		// (jitFnCompiler.ts:101).
		return ""
	}
	return WrapClosure(factoryName, innerFn, compiler.ContextLines())
}

// isImplemented reports whether dispatch_istype.go has a real emitter
// for the given kind. Mirrors the case list at the top of the EmitIsType
// switch — keep the two in sync when adding a new kind.
func isImplemented(kind protocol.ReflectionKind) bool {
	switch kind {
	case protocol.KindString:
		return true
	}
	return false
}

// lineWriter is the package-local equivalent of emit.bufWriter. The
// emit package keeps that type unexported, so jitfn mirrors the
// minimal contract here rather than reaching across packages for two
// methods.
type lineWriter struct {
	writer io.Writer
	err    error
}

func (lw *lineWriter) line(line string) {
	if lw.err != nil {
		return
	}
	_, lw.err = fmt.Fprintln(lw.writer, line)
}
