package jitfn

import (
	"fmt"
	"io"

	"github.com/mionkit/ts-run-types/internal/constants"
	"github.com/mionkit/ts-run-types/internal/protocol"
)

// isTypeInnerPrefix is the prefix for the INNER validator function
// inside each isType factory — what mion calls `jitFnHash` (the name
// used for self-recursive calls inside the body). The outer factory's
// name comes from CacheModules["isType"].VarPrefix (currently
// "get_isType_"). Keep the relationship
// `VarPrefix == "get_" + isTypeInnerPrefix` so the emitted JS matches
// mion's printClosure pattern (`get_<fnName>` wraps `<fnName>`).
//
// Each future fn module renderer defines its own inner prefix (e.g.
// `typeErrorsInnerPrefix = "typeErrors_"`). VarPrefix is consumer-
// facing (lives in CacheModuleSettings); the inner prefix is an
// internal codegen detail.
const isTypeInnerPrefix = "isType_"

// IsTypeModule writes the runtime artifact for the
// `virtual:runtypes-isType` module: one
// `export function get_isType_<hash>(utl) { … }` factory per RunType
// this package's IsTypeEmitter knows how to handle. Consumers import
// the factory and call it themselves with whatever `utl` they want
// bound into the closure — the module never pre-invokes a factory.
//
// Thin wrapper over RenderFnModule: every per-fn module renderer is
// one line once the Emitter is implemented. Adding typeErrors later
// is a one-line `TypeErrorsModule` next to this one.
func IsTypeModule(writer io.Writer, dump protocol.Dump) error {
	return RenderFnModule(writer, dump, constants.CacheModules["isType"], IsTypeEmitter{}, isTypeInnerPrefix)
}

// RenderFnModule is the fn-agnostic module renderer. Walks
// dump.RunTypes, builds a fresh Walker per supported RunType, wraps
// the compiled inner function in a `get_<factoryName>(utl) { … }`
// factory via WrapClosure, and writes one `export function …` per
// emitted factory.
//
// Kinds the emitter's Supports gate doesn't accept are silently
// skipped — the alternative (panicking) would crash the whole module
// for the presence of one unsupported kind, making kind-by-kind
// rollout impossible. The acceptance test in
// packages/vite-plugin-runtypes/test/jit-isType.test.ts asserts on
// the KindString case; if dispatch regresses for KindString the test
// fails loudly there.
//
// Parameters:
//   - settings: which CacheModule the factory names land in; the
//     VarPrefix becomes the exported factory's name prefix.
//   - emitter: the per-fn dispatch + Args + Finalize implementation.
//   - innerPrefix: the prefix for the INNER validator function inside
//     each factory (must satisfy
//     `settings.VarPrefix == "get_" + innerPrefix` for the
//     printClosure convention to hold).
func RenderFnModule(writer io.Writer, dump protocol.Dump, settings constants.CacheModuleSettings, emitter Emitter, innerPrefix string) error {
	buffered := &lineWriter{writer: writer}
	buffered.line("// Code generated by ts-go-run-types. DO NOT EDIT.")
	buffered.line("// Source: precompiled jit validators for mion runtypes.")
	buffered.line("")

	for _, runType := range dump.RunTypes {
		if runType == nil || !emitter.Supports(runType) {
			continue
		}
		factory := renderFactory(runType, settings, emitter, innerPrefix)
		if factory == "" {
			continue
		}
		buffered.line("export " + factory)
	}

	return buffered.err
}

// renderFactory compiles one RunType into a factory expression. The
// inner function lands as `<innerPrefix><hash>` (e.g. "isType_abc123");
// the outer factory lands as `<VarPrefix><hash>` (e.g.
// "get_isType_abc123"). Noop bodies — `function name(v){return true}`
// for isType, or analogous defaults for other fns — return an empty
// string so the renderer can skip them; consumers default to a
// trivial fallback on the JS side.
func renderFactory(runType *protocol.RunType, settings constants.CacheModuleSettings, emitter Emitter, innerPrefix string) string {
	factoryName := settings.VarPrefix + runType.ID
	innerName := innerPrefix + runType.ID
	walker := NewWalker(runType, innerName, emitter)
	innerFn, isNoop := walker.Compile()
	if isNoop {
		return ""
	}
	return WrapClosure(factoryName, innerFn, walker.ContextLines())
}

// lineWriter is the package-local equivalent of emit.bufWriter
// (internal/emit/runtypes_module.go:460). The emit package keeps that
// type unexported, so jitfn mirrors the minimal contract here rather
// than reaching across packages for two methods.
type lineWriter struct {
	writer io.Writer
	err    error
}

func (lw *lineWriter) line(line string) {
	if lw.err != nil {
		return
	}
	_, lw.err = fmt.Fprintln(lw.writer, line)
}
